from typing import Any

DESCRIPTOR: Any
PrimitiveType: Any
Format: Any
FftType: Any
RandomDistribution: Any
RandomAlgorithm: Any
PRIMITIVE_TYPE_INVALID: int
PRED: int
S8: int
S16: int
S32: int
S64: int
U8: int
U16: int
U32: int
U64: int
F16: int
F32: int
BF16: int
F64: int
C64: int
C128: int
TUPLE: int
OPAQUE_TYPE: int
TOKEN: int
INVALID_FORMAT: int
DENSE: int
FFT: int
IFFT: int
RFFT: int
IRFFT: int
RNG_INVALID: int
RNG_UNIFORM: int
RNG_NORMAL: int
RNG_DEFAULT: int
RNG_THREE_FRY: int
RNG_PHILOX: int
PaddingConfig: Any
TileProto: Any
LayoutProto: Any
ShapeProto: Any
ProgramShapeProto: Any
ComputationStats: Any
OpMetadata: Any
ExecutionProfile: Any
ExecutionHandle: Any
GlobalDataHandle: Any
DeviceHandle: Any
ChannelHandle: Any
DeviceAssignmentProto: Any
LiteralProto: Any
WindowDimension: Any
Window: Any
GatherDimensionNumbers: Any
ScatterDimensionNumbers: Any
ConvolutionDimensionNumbers: Any
DotDimensionNumbers: Any
TriangularSolveOptions: Any
CholeskyOptions: Any
FrontendAttributes: Any
OpSharding: Any
ReplicaGroup: Any
SourceTarget: Any
PrecisionConfig: Any
ParameterReplication: Any
WhileLoopBackendConfig: Any
