from typing import Any

class EventListenerStub:
    SendEvents: Any = ...
    SendTracebacks: Any = ...
    SendSourceFiles: Any = ...
    def __init__(self, channel: Any) -> None: ...

class EventListenerServicer:
    def SendEvents(self, request_iterator: Any, context: Any) -> None: ...
    def SendTracebacks(self, request: Any, context: Any) -> None: ...
    def SendSourceFiles(self, request: Any, context: Any) -> None: ...

def add_EventListenerServicer_to_server(servicer: Any, server: Any) -> None: ...
