from tensorflow.python.util import tf_contextlib as tf_contextlib
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any

def forward_compatible(year: Any, month: Any, day: Any): ...
def forward_compatibility_horizon(year: Any, month: Any, day: Any) -> None: ...
