from tensorflow.python.keras.utils import generic_utils as generic_utils
from typing import Any, Optional

def serialize(loss_scale: Any): ...
def deserialize(config: Any, custom_objects: Optional[Any] = ...): ...
def get(identifier: Any): ...
