from tensorflow.python.util.compat import collections_abc as collections_abc
from typing import Any

class KerasModeKeys:
    TRAIN: str = ...
    TEST: str = ...
    PREDICT: str = ...

class EstimatorModeKeys:
    TRAIN: str = ...
    EVAL: str = ...
    PREDICT: str = ...

def is_predict(mode: Any): ...
def is_eval(mode: Any): ...
def is_train(mode: Any): ...

class ModeKeyMap(collections_abc.Mapping):
    def __init__(self, **kwargs: Any) -> None: ...
    def __getitem__(self, key: Any): ...
    def __iter__(self) -> Any: ...
    def __len__(self): ...
