import abc
from tensorflow.python.keras.saving.saved_model import json_utils as json_utils
from tensorflow.python.training.tracking import tracking as tracking
from typing import Any

class SavedModelSaver(metaclass=abc.ABCMeta):
    obj: Any = ...
    def __init__(self, obj: Any) -> None: ...
    @property
    @abc.abstractmethod
    def object_identifier(self) -> Any: ...
    @property
    def tracking_metadata(self): ...
    def list_extra_dependencies_for_serialization(self, serialization_cache: Any): ...
    def list_functions_for_serialization(self, serialization_cache: Any): ...
    @property
    @abc.abstractmethod
    def python_properties(self) -> Any: ...
    @abc.abstractmethod
    def objects_to_serialize(self, serialization_cache: Any) -> Any: ...
    @abc.abstractmethod
    def functions_to_serialize(self, serialization_cache: Any) -> Any: ...
