from tensorflow.python.eager import def_function as def_function
from tensorflow.python.keras.saving.saved_model import constants as constants
from tensorflow.python.training.tracking.tracking import AutoTrackable as AutoTrackable
from tensorflow.python.util.lazy_loader import LazyLoader as LazyLoader
from typing import Any, Optional

base_layer: Any
training_lib: Any
metrics: Any
recurrent: Any

class SerializedAttributes:
    @staticmethod
    def with_attributes(name: Any, checkpointable_objects: Optional[Any] = ..., functions: Optional[Any] = ..., copy_from: Optional[Any] = ...): ...
    @staticmethod
    def new(obj: Any): ...
    def __init__(self) -> None: ...
    @property
    def functions(self): ...
    @property
    def checkpointable_objects(self): ...
    @property
    def functions_to_serialize(self): ...
    @property
    def objects_to_serialize(self): ...
    def set_and_validate_functions(self, function_dict: Any): ...
    def set_and_validate_objects(self, object_dict: Any): ...

class CommonEndpoints: ...
class LayerAttributes: ...
class ModelAttributes: ...
class MetricAttributes: ...
class RNNAttributes: ...
