from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any

class RaggedTensorValue:
    def __init__(self, values: Any, row_splits: Any) -> None: ...
    row_splits: Any = ...
    values: Any = ...
    dtype: Any = ...
    @property
    def flat_values(self): ...
    @property
    def nested_row_splits(self): ...
    @property
    def ragged_rank(self): ...
    @property
    def shape(self): ...
    def to_list(self): ...
