from tensorflow.python.framework import dtypes as dtypes, indexed_slices as indexed_slices, ops as ops
from tensorflow.python.ops import array_ops as array_ops, gen_ragged_conversion_ops as gen_ragged_conversion_ops, math_ops as math_ops
from tensorflow.python.ops.ragged import ragged_tensor as ragged_tensor
from typing import Any, Optional

def from_tensor(tensor: Any, lengths: Optional[Any] = ..., padding: Optional[Any] = ..., ragged_rank: int = ..., row_splits_dtype: Any = ..., name: Optional[Any] = ...): ...
def to_tensor(rt_input: Any, default_value: Optional[Any] = ..., name: Optional[Any] = ...): ...
def ragged_to_dense(rt_input: Any, default_value: Optional[Any] = ..., shape: Optional[Any] = ...): ...
def to_sparse(rt_input: Any, name: Optional[Any] = ...): ...
def from_sparse(st_input: Any, name: Optional[Any] = ...): ...
