from tensorflow.python.util.tf_export import keras_export as keras_export
from typing import Any, Optional

def model_from_config(config: Any, custom_objects: Optional[Any] = ...): ...
def model_from_yaml(yaml_string: Any, custom_objects: Optional[Any] = ...): ...
def model_from_json(json_string: Any, custom_objects: Optional[Any] = ...): ...
