from tensorflow.python.ops.linalg import linear_operator
from typing import Any, Optional

class LinearOperatorLowRankUpdate(linear_operator.LinearOperator):
    def __init__(self, base_operator: Any, u: Any, diag_update: Optional[Any] = ..., v: Optional[Any] = ..., is_diag_update_positive: Optional[Any] = ..., is_non_singular: Optional[Any] = ..., is_self_adjoint: Optional[Any] = ..., is_positive_definite: Optional[Any] = ..., is_square: Optional[Any] = ..., name: str = ...) -> None: ...
    @property
    def u(self): ...
    @property
    def v(self): ...
    @property
    def is_diag_update_positive(self): ...
    @property
    def diag_update(self): ...
    @property
    def diag_operator(self): ...
    @property
    def base_operator(self): ...
