from typing import Any

def combined_commuting_self_adjoint_hint(operator_a: Any, operator_b: Any): ...
def is_square(operator_a: Any, operator_b: Any): ...
def combined_commuting_positive_definite_hint(operator_a: Any, operator_b: Any): ...
def combined_non_singular_hint(operator_a: Any, operator_b: Any): ...
