from tensorflow.python.ops.distributions import special_math as special_math
from typing import Any

def test_moment_matching(samples: Any, number_moments: Any, dist: Any, stride: int = ...): ...
def chi_squared(x: Any, bins: Any): ...
def normal_cdf(x: Any): ...
def anderson_darling(x: Any): ...
def test_truncated_normal(assert_equal: Any, assert_all_close: Any, n: Any, y: Any, mean_atol: float = ..., median_atol: float = ..., variance_rtol: float = ...): ...
