from tensorflow.python.framework import ops as ops
from tensorflow.python.keras import backend as backend
from tensorflow.python.keras.engine import base_layer_utils as base_layer_utils
from tensorflow.python.util import nest as nest
from typing import Any, Optional

class Node:
    outbound_layer: Any = ...
    inbound_layers: Any = ...
    node_indices: Any = ...
    tensor_indices: Any = ...
    input_tensors: Any = ...
    output_tensors: Any = ...
    input_shapes: Any = ...
    output_shapes: Any = ...
    arguments: Any = ...
    def __init__(self, outbound_layer: Any, inbound_layers: Any, node_indices: Any, tensor_indices: Any, input_tensors: Any, output_tensors: Any, arguments: Optional[Any] = ...) -> None: ...
    def iterate_inbound(self, include_arguments: bool = ...): ...
    def get_config(self): ...
