from typing import Any

class ProfilerServiceStub:
    Profile: Any = ...
    Monitor: Any = ...
    def __init__(self, channel: Any) -> None: ...

class ProfilerServiceServicer:
    def Profile(self, request: Any, context: Any) -> None: ...
    def Monitor(self, request: Any, context: Any) -> None: ...

def add_ProfilerServiceServicer_to_server(servicer: Any, server: Any) -> None: ...
