import abc
from tensorflow.python.client import session as session
from tensorflow.python.eager import context as context
from tensorflow.python.framework import config as config, ops as ops
from tensorflow.python.training.server_lib import ClusterSpec as ClusterSpec
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any, Optional

def format_master_url(master: Any, rpc_layer: Optional[Any] = ...): ...
def get_accelerator_devices(master: Any, config_proto: Any): ...

class ClusterResolver(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def cluster_spec(self) -> Any: ...
    @abc.abstractmethod
    def master(self, task_type: Optional[Any] = ..., task_id: Optional[Any] = ..., rpc_layer: Optional[Any] = ...) -> Any: ...
    def num_accelerators(self, task_type: Optional[Any] = ..., task_id: Optional[Any] = ..., config_proto: Optional[Any] = ...): ...
    @property
    def environment(self): ...

class SimpleClusterResolver(ClusterResolver):
    def __init__(self, cluster_spec: Any, master: str = ..., task_type: Optional[Any] = ..., task_id: Optional[Any] = ..., environment: str = ..., num_accelerators: Optional[Any] = ..., rpc_layer: Optional[Any] = ...) -> None: ...
    def cluster_spec(self): ...
    def master(self, task_type: Optional[Any] = ..., task_id: Optional[Any] = ..., rpc_layer: Optional[Any] = ...): ...
    @property
    def task_type(self): ...
    @property
    def task_id(self): ...
    @task_type.setter
    def task_type(self, task_type: Any) -> None: ...
    @task_id.setter
    def task_id(self, task_id: Any) -> None: ...
    @property
    def environment(self): ...
    def num_accelerators(self, task_type: Optional[Any] = ..., task_id: Optional[Any] = ..., config_proto: Optional[Any] = ...): ...
    @property
    def rpc_layer(self): ...
    @rpc_layer.setter
    def rpc_layer(self, rpc_layer: Any) -> None: ...

class UnionClusterResolver(ClusterResolver):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def cluster_spec(self): ...
    def master(self, task_type: Optional[Any] = ..., task_id: Optional[Any] = ..., rpc_layer: Optional[Any] = ...): ...
    @property
    def task_type(self): ...
    @property
    def task_id(self): ...
    @task_type.setter
    def task_type(self, task_type: Any) -> None: ...
    @task_id.setter
    def task_id(self, task_id: Any) -> None: ...
    @property
    def environment(self): ...
    def num_accelerators(self, task_type: Optional[Any] = ..., task_id: Optional[Any] = ..., config_proto: Optional[Any] = ...): ...
    @property
    def rpc_layer(self): ...
    @rpc_layer.setter
    def rpc_layer(self, rpc_layer: Any) -> None: ...
