from typing import Any, Optional

def load_checkpoint(ckpt_dir_or_file: Any): ...
def load_variable(ckpt_dir_or_file: Any, name: Any): ...
def list_variables(ckpt_dir_or_file: Any): ...
def checkpoints_iterator(checkpoint_dir: Any, min_interval_secs: int = ..., timeout: Optional[Any] = ..., timeout_fn: Optional[Any] = ...) -> None: ...
def init_from_checkpoint(ckpt_dir_or_file: Any, assignment_map: Any): ...
