from tensorflow.python._pywrap_checkpoint_reader import CheckpointReader as CheckpointReader
from tensorflow.python.framework import dtypes as dtypes, errors_impl as errors_impl
from tensorflow.python.util import compat as compat
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any

def error_translator(e: Any) -> None: ...
def get_variable_to_dtype_map(self): ...
def has_tensor(self, tensor_str: Any): ...
def get_tensor(self, tensor_str: Any): ...
def NewCheckpointReader(filepattern: Any): ...
