from tensorflow.python.distribute import distribution_strategy_context as distribution_strategy_context
from tensorflow.python.ops import array_ops as array_ops, init_ops as init_ops, resource_variable_ops as resource_variable_ops, variable_scope as variable_scope, variables as variables
from typing import Any, Optional

def create_slot(primary: Any, val: Any, name: Any, colocate_with_primary: bool = ...): ...
def create_slot_with_initializer(primary: Any, initializer: Any, shape: Any, dtype: Any, name: Any, colocate_with_primary: bool = ...): ...
def create_zeros_slot(primary: Any, name: Any, dtype: Optional[Any] = ..., colocate_with_primary: bool = ...): ...
