import enum
from typing import Any, Optional

stacks: Any

def control_status_ctx(): ...

class Status(enum.Enum):
    UNSPECIFIED: int = ...
    ENABLED: int = ...
    DISABLED: int = ...

class ControlStatusCtx:
    status: Any = ...
    options: Any = ...
    def __init__(self, status: Any, options: Optional[Any] = ...) -> None: ...
    def __enter__(self): ...
    def __exit__(self, unused_type: Any, unused_value: Any, unused_traceback: Any) -> None: ...

class NullCtx:
    def __enter__(self) -> None: ...
    def __exit__(self, unused_type: Any, unused_value: Any, unused_traceback: Any) -> None: ...
