import enum
from typing import Any

class Rule:
    def __init__(self, module_prefix: Any) -> None: ...
    def matches(self, module_name: Any): ...

class Action(enum.Enum):
    NONE: int = ...
    CONVERT: int = ...
    DO_NOT_CONVERT: int = ...

class DoNotConvert(Rule):
    def get_action(self, module: Any): ...

class Convert(Rule):
    def get_action(self, module: Any): ...
