from tensorflow.python.autograph.core import ag_ctx as ag_ctx, converter as converter
from tensorflow.python.framework import auto_control_deps as auto_control_deps, ops as ops, tensor_util as tensor_util
from tensorflow.python.util import nest as nest
from typing import Any

class FunctionScope:
    name: Any = ...
    options: Any = ...
    autograph_ctx: Any = ...
    callopts: Any = ...
    use_name_scope: Any = ...
    name_scope: Any = ...
    use_auto_deps: Any = ...
    autodeps_scope: Any = ...
    def __init__(self, function_name: Any, scope_name: Any, options: Any) -> None: ...
    def __enter__(self): ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...
    def mark_return_value(self, value: Any): ...

def with_function_scope(thunk: Any, scope_name: Any, options: Any): ...
