import enum
from tensorflow.python.autograph.pyct import qual_names as qual_names
from tensorflow.python.autograph.utils import misc as misc
from typing import Any

class _NamingStyle(enum.Enum):
    SNAKE: int = ...
    CAMEL: int = ...

class Namer:
    global_namespace: Any = ...
    generated_names: Any = ...
    def __init__(self, global_namespace: Any) -> None: ...
    def class_name(self, original_fqn: Any): ...
    def function_name(self, original_fqn: Any): ...
    def new_symbol(self, name_root: Any, reserved_locals: Any): ...
