import gast
from tensorflow.python.autograph.pyct import errors as errors
from typing import Any

class UnsupportedFeaturesChecker(gast.NodeVisitor):
    def visit_Attribute(self, node: Any) -> None: ...
    def visit_For(self, node: Any) -> None: ...
    def visit_While(self, node: Any) -> None: ...
    def visit_Yield(self, node: Any) -> None: ...
    def visit_YieldFrom(self, node: Any) -> None: ...

def verify(node: Any) -> None: ...
