from tensorflow.python.data.ops import dataset_ops as dataset_ops
from tensorflow.python.keras.layers.preprocessing import image_preprocessing as image_preprocessing
from tensorflow.python.ops import array_ops as array_ops, image_ops as image_ops, io_ops as io_ops, math_ops as math_ops
from tensorflow.python.util.tf_export import keras_export as keras_export
from typing import Any, Optional

WHITELIST_FORMATS: Any

def dataset_from_directory(directory: Any, labels: str = ..., label_mode: str = ..., class_names: Optional[Any] = ..., color_mode: str = ..., batch_size: int = ..., image_size: Any = ..., shuffle: bool = ..., seed: Optional[Any] = ..., validation_split: Optional[Any] = ..., subset: Optional[Any] = ..., interpolation: str = ..., follow_links: bool = ...): ...
def paths_and_labels_to_dataset(image_paths: Any, image_size: Any, num_channels: Any, labels: Any, label_mode: Any, num_classes: Any, interpolation: Any): ...
def iter_valid_files(directory: Any, follow_links: Any): ...
def list_labeled_images_in_directory(directory: Any, class_indices: Any, follow_links: Any): ...
def path_to_image(path: Any, image_size: Any, num_channels: Any, interpolation: Any): ...
