from tensorflow.python.eager import context as context
from tensorflow.python.framework import dtypes as dtypes, ops as ops
from tensorflow.python.keras import backend as backend
from tensorflow.python.keras.engine import base_layer as base_layer
from tensorflow.python.keras.mixed_precision.experimental import policy as policy
from tensorflow.python.util import deprecation as deprecation, function_utils as function_utils, nest as nest, tf_contextlib as tf_contextlib
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any, Optional

InputSpec: Any

def keras_style_scope() -> None: ...
def set_keras_style() -> None: ...

class Layer(base_layer.Layer):
    built: bool = ...
    def __init__(self, trainable: bool = ..., name: Optional[Any] = ..., dtype: Optional[Any] = ..., **kwargs: Any) -> None: ...
    @property
    def graph(self) -> None: ...
    @property
    def scope_name(self): ...
    def add_loss(self, losses: Any, inputs: Optional[Any] = ...) -> None: ...
    def add_weight(self, name: Any, shape: Any, dtype: Optional[Any] = ..., initializer: Optional[Any] = ..., regularizer: Optional[Any] = ..., trainable: Optional[Any] = ..., constraint: Optional[Any] = ..., use_resource: Optional[Any] = ..., synchronization: Any = ..., aggregation: Any = ..., partitioner: Optional[Any] = ..., **kwargs: Any): ...
    def __call__(self, inputs: Any, *args: Any, **kwargs: Any): ...
    def __deepcopy__(self, memo: Any): ...
    def __setattr__(self, value: Any, name: Any) -> None: ...
