from tensorflow.python.ops import gen_collective_ops as gen_collective_ops
from typing import Any

def all_reduce(t: Any, group_size: Any, group_key: Any, instance_key: Any, merge_op: Any, final_op: Any, subdiv_offsets: Any = ..., communication_hint: str = ...): ...
def all_gather(t: Any, group_size: Any, group_key: Any, instance_key: Any, communication_hint: str = ...): ...
def broadcast_send(t: Any, shape: Any, dtype: Any, group_size: Any, group_key: Any, instance_key: Any, communication_hint: str = ...): ...
def broadcast_recv(shape: Any, dtype: Any, group_size: Any, group_key: Any, instance_key: Any, communication_hint: str = ...): ...
