from tensorflow.python import tf2 as tf2
from typing import Any, Optional

ENABLE_CONTROL_FLOW_V2: Any

def enable_control_flow_v2() -> None: ...
def EnableControlFlowV2(graph: Any): ...
def IsInXLAContext(op: Any): ...
def InXlaContext(graph: Any): ...
def GraphOrParentsInXlaContext(graph: Any): ...
def IsInWhileLoop(op: Any): ...
def IsInCond(op: Any): ...
def IsSwitch(op: Any): ...
def IsMerge(op: Any): ...
def IsLoopEnter(op: Any): ...
def IsLoopExit(op: Any): ...
def IsCondSwitch(op: Any): ...
def IsCondMerge(op: Any): ...
def IsLoopSwitch(op: Any): ...
def IsLoopMerge(op: Any): ...
def IsLoopConstantEnter(op: Any): ...
def GetLoopConstantEnter(value: Any): ...
def GetOutputContext(op: Any): ...
def GetContainingWhileContext(ctxt: Any, stop_ctxt: Optional[Any] = ...): ...
def GetContainingXLAContext(ctxt: Any): ...
def GetContainingCondContext(ctxt: Any): ...
def IsContainingContext(ctxt: Any, maybe_containing_ctxt: Any): ...
def OpInContext(op: Any, ctxt: Any): ...
def TensorInContext(tensor: Any, ctxt: Any): ...
def CheckInputFromValidContext(op: Any, input_op: Any) -> None: ...
def GetWhileContext(op: Any): ...
