from typing import Any, Optional

class _ExecutionSignature: ...

class CriticalSection:
    def __init__(self, name: Optional[Any] = ..., shared_name: Optional[Any] = ..., critical_section_def: Optional[Any] = ..., import_scope: Optional[Any] = ...) -> None: ...
    @property
    def name(self): ...
    def execute(self, fn: Any, exclusive_resource_access: bool = ..., name: Optional[Any] = ...): ...
