from tensorflow.python.framework import dtypes as dtypes, tensor_shape as tensor_shape
from tensorflow.python.ops import array_ops as array_ops, resource_variable_ops as resource_variable_ops
from typing import Any

def get_zeros_dtype(t: Any): ...
def shape_and_dtype(t: Any): ...
def zeros_like(t: Any): ...
def ones_like(t: Any): ...
def supports_default_grad(t: Any): ...
