from collections import namedtuple
from tensorflow.python.util.deprecation import deprecated_endpoints as deprecated_endpoints
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any, Optional

def hash_table(key_dtype: Any, value_dtype: Any, container: str = ..., shared_name: str = ..., use_node_name_sharing: bool = ..., name: Optional[Any] = ...): ...

HashTable: Any

def hash_table_eager_fallback(key_dtype: Any, value_dtype: Any, container: Any, shared_name: Any, use_node_name_sharing: Any, name: Any, ctx: Any) -> None: ...
def hash_table_v2(key_dtype: Any, value_dtype: Any, container: str = ..., shared_name: str = ..., use_node_name_sharing: bool = ..., name: Optional[Any] = ...): ...

HashTableV2: Any

def hash_table_v2_eager_fallback(key_dtype: Any, value_dtype: Any, container: Any, shared_name: Any, use_node_name_sharing: Any, name: Any, ctx: Any): ...
def initialize_table(table_handle: Any, keys: Any, values: Any, name: Optional[Any] = ...): ...

InitializeTable: Any

def initialize_table_eager_fallback(table_handle: Any, keys: Any, values: Any, name: Any, ctx: Any) -> None: ...
def initialize_table_from_text_file(table_handle: Any, filename: Any, key_index: Any, value_index: Any, vocab_size: int = ..., delimiter: str = ..., name: Optional[Any] = ...): ...

InitializeTableFromTextFile: Any

def initialize_table_from_text_file_eager_fallback(table_handle: Any, filename: Any, key_index: Any, value_index: Any, vocab_size: Any, delimiter: Any, name: Any, ctx: Any) -> None: ...
def initialize_table_from_text_file_v2(table_handle: Any, filename: Any, key_index: Any, value_index: Any, vocab_size: int = ..., delimiter: str = ..., name: Optional[Any] = ...): ...

InitializeTableFromTextFileV2: Any

def initialize_table_from_text_file_v2_eager_fallback(table_handle: Any, filename: Any, key_index: Any, value_index: Any, vocab_size: Any, delimiter: Any, name: Any, ctx: Any): ...
def initialize_table_v2(table_handle: Any, keys: Any, values: Any, name: Optional[Any] = ...): ...

InitializeTableV2: Any

def initialize_table_v2_eager_fallback(table_handle: Any, keys: Any, values: Any, name: Any, ctx: Any): ...

_LookupTableExportOutput = namedtuple('LookupTableExport', ['keys', 'values'])

def lookup_table_export(table_handle: Any, Tkeys: Any, Tvalues: Any, name: Optional[Any] = ...): ...

LookupTableExport: Any

def lookup_table_export_eager_fallback(table_handle: Any, Tkeys: Any, Tvalues: Any, name: Any, ctx: Any) -> None: ...

_LookupTableExportV2Output = namedtuple('LookupTableExportV2', ['keys', 'values'])

def lookup_table_export_v2(table_handle: Any, Tkeys: Any, Tvalues: Any, name: Optional[Any] = ...): ...

LookupTableExportV2: Any

def lookup_table_export_v2_eager_fallback(table_handle: Any, Tkeys: Any, Tvalues: Any, name: Any, ctx: Any): ...
def lookup_table_find(table_handle: Any, keys: Any, default_value: Any, name: Optional[Any] = ...): ...

LookupTableFind: Any

def lookup_table_find_eager_fallback(table_handle: Any, keys: Any, default_value: Any, name: Any, ctx: Any) -> None: ...
def lookup_table_find_v2(table_handle: Any, keys: Any, default_value: Any, name: Optional[Any] = ...): ...

LookupTableFindV2: Any

def lookup_table_find_v2_eager_fallback(table_handle: Any, keys: Any, default_value: Any, name: Any, ctx: Any): ...
def lookup_table_import(table_handle: Any, keys: Any, values: Any, name: Optional[Any] = ...): ...

LookupTableImport: Any

def lookup_table_import_eager_fallback(table_handle: Any, keys: Any, values: Any, name: Any, ctx: Any) -> None: ...
def lookup_table_import_v2(table_handle: Any, keys: Any, values: Any, name: Optional[Any] = ...): ...

LookupTableImportV2: Any

def lookup_table_import_v2_eager_fallback(table_handle: Any, keys: Any, values: Any, name: Any, ctx: Any): ...
def lookup_table_insert(table_handle: Any, keys: Any, values: Any, name: Optional[Any] = ...): ...

LookupTableInsert: Any

def lookup_table_insert_eager_fallback(table_handle: Any, keys: Any, values: Any, name: Any, ctx: Any) -> None: ...
def lookup_table_insert_v2(table_handle: Any, keys: Any, values: Any, name: Optional[Any] = ...): ...

LookupTableInsertV2: Any

def lookup_table_insert_v2_eager_fallback(table_handle: Any, keys: Any, values: Any, name: Any, ctx: Any): ...
def lookup_table_remove_v2(table_handle: Any, keys: Any, name: Optional[Any] = ...): ...

LookupTableRemoveV2: Any

def lookup_table_remove_v2_eager_fallback(table_handle: Any, keys: Any, name: Any, ctx: Any): ...
def lookup_table_size(table_handle: Any, name: Optional[Any] = ...): ...

LookupTableSize: Any

def lookup_table_size_eager_fallback(table_handle: Any, name: Any, ctx: Any) -> None: ...
def lookup_table_size_v2(table_handle: Any, name: Optional[Any] = ...): ...

LookupTableSizeV2: Any

def lookup_table_size_v2_eager_fallback(table_handle: Any, name: Any, ctx: Any): ...
def mutable_dense_hash_table(empty_key: Any, value_dtype: Any, container: str = ..., shared_name: str = ..., use_node_name_sharing: bool = ..., value_shape: Any = ..., initial_num_buckets: int = ..., max_load_factor: float = ..., name: Optional[Any] = ...): ...

MutableDenseHashTable: Any

def mutable_dense_hash_table_eager_fallback(empty_key: Any, value_dtype: Any, container: Any, shared_name: Any, use_node_name_sharing: Any, value_shape: Any, initial_num_buckets: Any, max_load_factor: Any, name: Any, ctx: Any) -> None: ...
def mutable_dense_hash_table_v2(empty_key: Any, deleted_key: Any, value_dtype: Any, container: str = ..., shared_name: str = ..., use_node_name_sharing: bool = ..., value_shape: Any = ..., initial_num_buckets: int = ..., max_load_factor: float = ..., name: Optional[Any] = ...): ...

MutableDenseHashTableV2: Any

def mutable_dense_hash_table_v2_eager_fallback(empty_key: Any, deleted_key: Any, value_dtype: Any, container: Any, shared_name: Any, use_node_name_sharing: Any, value_shape: Any, initial_num_buckets: Any, max_load_factor: Any, name: Any, ctx: Any): ...
def mutable_hash_table(key_dtype: Any, value_dtype: Any, container: str = ..., shared_name: str = ..., use_node_name_sharing: bool = ..., name: Optional[Any] = ...): ...

MutableHashTable: Any

def mutable_hash_table_eager_fallback(key_dtype: Any, value_dtype: Any, container: Any, shared_name: Any, use_node_name_sharing: Any, name: Any, ctx: Any) -> None: ...
def mutable_hash_table_of_tensors(key_dtype: Any, value_dtype: Any, container: str = ..., shared_name: str = ..., use_node_name_sharing: bool = ..., value_shape: Any = ..., name: Optional[Any] = ...): ...

MutableHashTableOfTensors: Any

def mutable_hash_table_of_tensors_eager_fallback(key_dtype: Any, value_dtype: Any, container: Any, shared_name: Any, use_node_name_sharing: Any, value_shape: Any, name: Any, ctx: Any) -> None: ...
def mutable_hash_table_of_tensors_v2(key_dtype: Any, value_dtype: Any, container: str = ..., shared_name: str = ..., use_node_name_sharing: bool = ..., value_shape: Any = ..., name: Optional[Any] = ...): ...

MutableHashTableOfTensorsV2: Any

def mutable_hash_table_of_tensors_v2_eager_fallback(key_dtype: Any, value_dtype: Any, container: Any, shared_name: Any, use_node_name_sharing: Any, value_shape: Any, name: Any, ctx: Any): ...
def mutable_hash_table_v2(key_dtype: Any, value_dtype: Any, container: str = ..., shared_name: str = ..., use_node_name_sharing: bool = ..., name: Optional[Any] = ...): ...

MutableHashTableV2: Any

def mutable_hash_table_v2_eager_fallback(key_dtype: Any, value_dtype: Any, container: Any, shared_name: Any, use_node_name_sharing: Any, name: Any, ctx: Any): ...
