from tensorflow.python.util.deprecation import deprecated_endpoints as deprecated_endpoints
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any, Optional

def bitwise_and(x: Any, y: Any, name: Optional[Any] = ...): ...

BitwiseAnd: Any

def bitwise_and_eager_fallback(x: Any, y: Any, name: Any, ctx: Any): ...
def bitwise_or(x: Any, y: Any, name: Optional[Any] = ...): ...

BitwiseOr: Any

def bitwise_or_eager_fallback(x: Any, y: Any, name: Any, ctx: Any): ...
def bitwise_xor(x: Any, y: Any, name: Optional[Any] = ...): ...

BitwiseXor: Any

def bitwise_xor_eager_fallback(x: Any, y: Any, name: Any, ctx: Any): ...
def invert(x: Any, name: Optional[Any] = ...): ...

Invert: Any

def invert_eager_fallback(x: Any, name: Any, ctx: Any): ...
def left_shift(x: Any, y: Any, name: Optional[Any] = ...): ...

LeftShift: Any

def left_shift_eager_fallback(x: Any, y: Any, name: Any, ctx: Any): ...
def population_count(x: Any, name: Optional[Any] = ...): ...

PopulationCount: Any

def population_count_eager_fallback(x: Any, name: Any, ctx: Any): ...
def right_shift(x: Any, y: Any, name: Optional[Any] = ...): ...

RightShift: Any

def right_shift_eager_fallback(x: Any, y: Any, name: Any, ctx: Any): ...
