from tensorflow.python.util.deprecation import deprecated_endpoints as deprecated_endpoints
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any, Optional

def dawsn(x: Any, name: Optional[Any] = ...): ...

Dawsn: Any

def dawsn_eager_fallback(x: Any, name: Any, ctx: Any): ...
def expint(x: Any, name: Optional[Any] = ...): ...

Expint: Any

def expint_eager_fallback(x: Any, name: Any, ctx: Any): ...
def fresnel_cos(x: Any, name: Optional[Any] = ...): ...

FresnelCos: Any

def fresnel_cos_eager_fallback(x: Any, name: Any, ctx: Any): ...
def fresnel_sin(x: Any, name: Optional[Any] = ...): ...

FresnelSin: Any

def fresnel_sin_eager_fallback(x: Any, name: Any, ctx: Any): ...
def spence(x: Any, name: Optional[Any] = ...): ...

Spence: Any

def spence_eager_fallback(x: Any, name: Any, ctx: Any): ...
