from tensorflow.python.util.deprecation import deprecated_endpoints as deprecated_endpoints
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any, Optional

def batch_fft(input: Any, name: Optional[Any] = ...): ...

BatchFFT: Any

def batch_fft_eager_fallback(input: Any, name: Any, ctx: Any): ...
def batch_fft2d(input: Any, name: Optional[Any] = ...): ...

BatchFFT2D: Any

def batch_fft2d_eager_fallback(input: Any, name: Any, ctx: Any): ...
def batch_fft3d(input: Any, name: Optional[Any] = ...): ...

BatchFFT3D: Any

def batch_fft3d_eager_fallback(input: Any, name: Any, ctx: Any): ...
def batch_ifft(input: Any, name: Optional[Any] = ...): ...

BatchIFFT: Any

def batch_ifft_eager_fallback(input: Any, name: Any, ctx: Any): ...
def batch_ifft2d(input: Any, name: Optional[Any] = ...): ...

BatchIFFT2D: Any

def batch_ifft2d_eager_fallback(input: Any, name: Any, ctx: Any): ...
def batch_ifft3d(input: Any, name: Optional[Any] = ...): ...

BatchIFFT3D: Any

def batch_ifft3d_eager_fallback(input: Any, name: Any, ctx: Any): ...
def fft(input: Any, name: Optional[Any] = ...): ...

FFT: Any

def fft_eager_fallback(input: Any, name: Any, ctx: Any): ...
def fft2d(input: Any, name: Optional[Any] = ...): ...

FFT2D: Any

def fft2d_eager_fallback(input: Any, name: Any, ctx: Any): ...
def fft3d(input: Any, name: Optional[Any] = ...): ...

FFT3D: Any

def fft3d_eager_fallback(input: Any, name: Any, ctx: Any): ...
def ifft(input: Any, name: Optional[Any] = ...): ...

IFFT: Any

def ifft_eager_fallback(input: Any, name: Any, ctx: Any): ...
def ifft2d(input: Any, name: Optional[Any] = ...): ...

IFFT2D: Any

def ifft2d_eager_fallback(input: Any, name: Any, ctx: Any): ...
def ifft3d(input: Any, name: Optional[Any] = ...): ...

IFFT3D: Any

def ifft3d_eager_fallback(input: Any, name: Any, ctx: Any): ...
def irfft(input: Any, fft_length: Any, Treal: Any = ..., name: Optional[Any] = ...): ...

IRFFT: Any

def irfft_eager_fallback(input: Any, fft_length: Any, Treal: Any, name: Any, ctx: Any): ...
def irfft2d(input: Any, fft_length: Any, Treal: Any = ..., name: Optional[Any] = ...): ...

IRFFT2D: Any

def irfft2d_eager_fallback(input: Any, fft_length: Any, Treal: Any, name: Any, ctx: Any): ...
def irfft3d(input: Any, fft_length: Any, Treal: Any = ..., name: Optional[Any] = ...): ...

IRFFT3D: Any

def irfft3d_eager_fallback(input: Any, fft_length: Any, Treal: Any, name: Any, ctx: Any): ...
def rfft(input: Any, fft_length: Any, Tcomplex: Any = ..., name: Optional[Any] = ...): ...

RFFT: Any

def rfft_eager_fallback(input: Any, fft_length: Any, Tcomplex: Any, name: Any, ctx: Any): ...
def rfft2d(input: Any, fft_length: Any, Tcomplex: Any = ..., name: Optional[Any] = ...): ...

RFFT2D: Any

def rfft2d_eager_fallback(input: Any, fft_length: Any, Tcomplex: Any, name: Any, ctx: Any): ...
def rfft3d(input: Any, fft_length: Any, Tcomplex: Any = ..., name: Optional[Any] = ...): ...

RFFT3D: Any

def rfft3d_eager_fallback(input: Any, fft_length: Any, Tcomplex: Any, name: Any, ctx: Any): ...
