from tensorflow.python.util.deprecation import deprecated_endpoints as deprecated_endpoints
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any, Optional

def close_summary_writer(writer: Any, name: Optional[Any] = ...): ...

CloseSummaryWriter: Any

def close_summary_writer_eager_fallback(writer: Any, name: Any, ctx: Any): ...
def create_summary_db_writer(writer: Any, db_uri: Any, experiment_name: Any, run_name: Any, user_name: Any, name: Optional[Any] = ...): ...

CreateSummaryDbWriter: Any

def create_summary_db_writer_eager_fallback(writer: Any, db_uri: Any, experiment_name: Any, run_name: Any, user_name: Any, name: Any, ctx: Any): ...
def create_summary_file_writer(writer: Any, logdir: Any, max_queue: Any, flush_millis: Any, filename_suffix: Any, name: Optional[Any] = ...): ...

CreateSummaryFileWriter: Any

def create_summary_file_writer_eager_fallback(writer: Any, logdir: Any, max_queue: Any, flush_millis: Any, filename_suffix: Any, name: Any, ctx: Any): ...
def flush_summary_writer(writer: Any, name: Optional[Any] = ...): ...

FlushSummaryWriter: Any

def flush_summary_writer_eager_fallback(writer: Any, name: Any, ctx: Any): ...
def import_event(writer: Any, event: Any, name: Optional[Any] = ...): ...

ImportEvent: Any

def import_event_eager_fallback(writer: Any, event: Any, name: Any, ctx: Any): ...
def summary_writer(shared_name: str = ..., container: str = ..., name: Optional[Any] = ...): ...

SummaryWriter: Any

def summary_writer_eager_fallback(shared_name: Any, container: Any, name: Any, ctx: Any): ...
def write_audio_summary(writer: Any, step: Any, tag: Any, tensor: Any, sample_rate: Any, max_outputs: int = ..., name: Optional[Any] = ...): ...

WriteAudioSummary: Any

def write_audio_summary_eager_fallback(writer: Any, step: Any, tag: Any, tensor: Any, sample_rate: Any, max_outputs: Any, name: Any, ctx: Any): ...
def write_graph_summary(writer: Any, step: Any, tensor: Any, name: Optional[Any] = ...): ...

WriteGraphSummary: Any

def write_graph_summary_eager_fallback(writer: Any, step: Any, tensor: Any, name: Any, ctx: Any): ...
def write_histogram_summary(writer: Any, step: Any, tag: Any, values: Any, name: Optional[Any] = ...): ...

WriteHistogramSummary: Any

def write_histogram_summary_eager_fallback(writer: Any, step: Any, tag: Any, values: Any, name: Any, ctx: Any): ...
def write_image_summary(writer: Any, step: Any, tag: Any, tensor: Any, bad_color: Any, max_images: int = ..., name: Optional[Any] = ...): ...

WriteImageSummary: Any

def write_image_summary_eager_fallback(writer: Any, step: Any, tag: Any, tensor: Any, bad_color: Any, max_images: Any, name: Any, ctx: Any): ...
def write_raw_proto_summary(writer: Any, step: Any, tensor: Any, name: Optional[Any] = ...): ...

WriteRawProtoSummary: Any

def write_raw_proto_summary_eager_fallback(writer: Any, step: Any, tensor: Any, name: Any, ctx: Any): ...
def write_scalar_summary(writer: Any, step: Any, tag: Any, value: Any, name: Optional[Any] = ...): ...

WriteScalarSummary: Any

def write_scalar_summary_eager_fallback(writer: Any, step: Any, tag: Any, value: Any, name: Any, ctx: Any): ...
def write_summary(writer: Any, step: Any, tensor: Any, tag: Any, summary_metadata: Any, name: Optional[Any] = ...): ...

WriteSummary: Any

def write_summary_eager_fallback(writer: Any, step: Any, tensor: Any, tag: Any, summary_metadata: Any, name: Any, ctx: Any): ...
