from tensorflow.python.util.deprecation import deprecated_endpoints as deprecated_endpoints
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any, Optional

def collective_bcast_recv(T: Any, group_size: Any, group_key: Any, instance_key: Any, shape: Any, communication_hint: str = ..., name: Optional[Any] = ...): ...

CollectiveBcastRecv: Any

def collective_bcast_recv_eager_fallback(T: Any, group_size: Any, group_key: Any, instance_key: Any, shape: Any, communication_hint: Any, name: Any, ctx: Any): ...
def collective_bcast_send(input: Any, group_size: Any, group_key: Any, instance_key: Any, shape: Any, communication_hint: str = ..., name: Optional[Any] = ...): ...

CollectiveBcastSend: Any

def collective_bcast_send_eager_fallback(input: Any, group_size: Any, group_key: Any, instance_key: Any, shape: Any, communication_hint: Any, name: Any, ctx: Any): ...
def collective_gather(input: Any, group_size: Any, group_key: Any, instance_key: Any, shape: Any, communication_hint: str = ..., name: Optional[Any] = ...): ...

CollectiveGather: Any

def collective_gather_eager_fallback(input: Any, group_size: Any, group_key: Any, instance_key: Any, shape: Any, communication_hint: Any, name: Any, ctx: Any): ...
def collective_reduce(input: Any, group_size: Any, group_key: Any, instance_key: Any, merge_op: Any, final_op: Any, subdiv_offsets: Any, wait_for: Any = ..., communication_hint: str = ..., name: Optional[Any] = ...): ...

CollectiveReduce: Any

def collective_reduce_eager_fallback(input: Any, group_size: Any, group_key: Any, instance_key: Any, merge_op: Any, final_op: Any, subdiv_offsets: Any, wait_for: Any, communication_hint: Any, name: Any, ctx: Any): ...
