from tensorflow.python.util.deprecation import deprecated_endpoints as deprecated_endpoints
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any, Optional

def tensor_forest_create_tree_variable(tree_handle: Any, tree_config: Any, name: Optional[Any] = ...): ...

TensorForestCreateTreeVariable: Any

def tensor_forest_create_tree_variable_eager_fallback(tree_handle: Any, tree_config: Any, name: Any, ctx: Any): ...
def tensor_forest_tree_deserialize(tree_handle: Any, tree_config: Any, name: Optional[Any] = ...): ...

TensorForestTreeDeserialize: Any

def tensor_forest_tree_deserialize_eager_fallback(tree_handle: Any, tree_config: Any, name: Any, ctx: Any): ...
def tensor_forest_tree_is_initialized_op(tree_handle: Any, name: Optional[Any] = ...): ...

TensorForestTreeIsInitializedOp: Any

def tensor_forest_tree_is_initialized_op_eager_fallback(tree_handle: Any, name: Any, ctx: Any): ...
def tensor_forest_tree_predict(tree_handle: Any, dense_features: Any, logits_dimension: Any, name: Optional[Any] = ...): ...

TensorForestTreePredict: Any

def tensor_forest_tree_predict_eager_fallback(tree_handle: Any, dense_features: Any, logits_dimension: Any, name: Any, ctx: Any): ...
def tensor_forest_tree_resource_handle_op(container: str = ..., shared_name: str = ..., name: Optional[Any] = ...): ...

TensorForestTreeResourceHandleOp: Any

def tensor_forest_tree_resource_handle_op_eager_fallback(container: Any, shared_name: Any, name: Any, ctx: Any): ...
def tensor_forest_tree_serialize(tree_handle: Any, name: Optional[Any] = ...): ...

TensorForestTreeSerialize: Any

def tensor_forest_tree_serialize_eager_fallback(tree_handle: Any, name: Any, ctx: Any): ...
def tensor_forest_tree_size(tree_handle: Any, name: Optional[Any] = ...): ...

TensorForestTreeSize: Any

def tensor_forest_tree_size_eager_fallback(tree_handle: Any, name: Any, ctx: Any): ...
