from tensorflow.python.framework import dtypes as dtypes, ops as ops
from tensorflow.python.ops import array_grad as array_grad, array_ops as array_ops, check_ops as check_ops, control_flow_grad as control_flow_grad, control_flow_ops as control_flow_ops, gradients_util as gradients_util, image_grad as image_grad, linalg_grad as linalg_grad, linalg_ops as linalg_ops, logging_ops as logging_ops, manip_grad as manip_grad, math_grad as math_grad, math_ops as math_ops, optional_grad as optional_grad, random_grad as random_grad, tensor_array_ops as tensor_array_ops
from tensorflow.python.ops.unconnected_gradients import UnconnectedGradients as UnconnectedGradients
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any, Optional

def gradients(ys: Any, xs: Any, grad_ys: Optional[Any] = ..., name: str = ..., colocate_gradients_with_ops: bool = ..., gate_gradients: bool = ..., aggregation_method: Optional[Any] = ..., stop_gradients: Optional[Any] = ..., unconnected_gradients: Any = ...): ...
def gradients_v2(ys: Any, xs: Any, grad_ys: Optional[Any] = ..., name: str = ..., gate_gradients: bool = ..., aggregation_method: Optional[Any] = ..., stop_gradients: Optional[Any] = ..., unconnected_gradients: Any = ...): ...
def hessians(ys: Any, xs: Any, name: str = ..., colocate_gradients_with_ops: bool = ..., gate_gradients: bool = ..., aggregation_method: Optional[Any] = ...): ...
def HessiansV2(ys: Any, xs: Any, gate_gradients: bool = ..., aggregation_method: Optional[Any] = ..., name: str = ...): ...
