from typing import Any, Optional

def variable_axis_size_partitioner(max_shard_bytes: Any, axis: int = ..., bytes_per_string_element: int = ..., max_shards: Optional[Any] = ...): ...
def min_max_variable_partitioner(max_partitions: int = ..., axis: int = ..., min_slice_size: Any = ..., bytes_per_string_element: int = ...): ...
def fixed_size_partitioner(num_shards: Any, axis: int = ...): ...
def create_partitioned_variables(shape: Any, slicing: Any, initializer: Any, dtype: Any = ..., trainable: bool = ..., collections: Optional[Any] = ..., name: Optional[Any] = ..., reuse: Optional[Any] = ...): ...
