from tensorflow.compiler.tf2xla.ops import gen_xla_ops as gen_xla_ops
from tensorflow.python.framework import ops as ops, tensor_shape as tensor_shape
from tensorflow.python.ops import array_ops as array_ops, control_flow_ops as control_flow_ops, gen_linalg_ops as gen_linalg_ops, gen_special_math_ops as gen_special_math_ops, math_ops as math_ops
from tensorflow.python.util import deprecation as deprecation
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any, Optional

def lbeta(x: Any, name: Optional[Any] = ...): ...
def dawsn(x: Any, name: Optional[Any] = ...): ...
def expint(x: Any, name: Optional[Any] = ...): ...
def fresnel_cos(x: Any, name: Optional[Any] = ...): ...
def fresnel_sin(x: Any, name: Optional[Any] = ...): ...
def spence(x: Any, name: Optional[Any] = ...): ...
def bessel_i0(x: Any, name: Optional[Any] = ...): ...
def bessel_i1(x: Any, name: Optional[Any] = ...): ...
def einsum(equation: Any, *inputs: Any, **kwargs: Any): ...
