from tensorflow.python import ops as ops
from tensorflow.python.ops import gen_tensor_forest_ops as gen_tensor_forest_ops, resources as resources
from tensorflow.python.training import saver as saver
from typing import Any, Optional

class TreeVariableSaveable(saver.BaseSaverBuilder.SaveableObject):
    def __init__(self, type_name: Any, name: Any, container: Any, config: Any, resource_handle_func: Any, create_op_func: Any, is_initialized_op_func: Any, serialize_op_func: Any, deserialize_op_func: Any) -> None: ...
    def restore(self, restored_tensors: Any, unused_restored_shapes: Any): ...
    @property
    def resource(self): ...

def tree_variable(tree_config: Any, name: Any, container: Optional[Any] = ...): ...

class ForestVariables:
    def __init__(self, params: Any, tree_configs: Optional[Any] = ...) -> None: ...
    def __getitem__(self, t: Any): ...
