from tensorflow.python.keras import backend as backend, layers as layers
from tensorflow.python.keras.applications import imagenet_utils as imagenet_utils
from tensorflow.python.keras.engine import training as training
from tensorflow.python.keras.utils import data_utils as data_utils, layer_utils as layer_utils
from tensorflow.python.util.tf_export import keras_export as keras_export
from typing import Any, Optional

BASE_WEIGTHS_PATH: str
DENSENET121_WEIGHT_PATH: Any
DENSENET121_WEIGHT_PATH_NO_TOP: Any
DENSENET169_WEIGHT_PATH: Any
DENSENET169_WEIGHT_PATH_NO_TOP: Any
DENSENET201_WEIGHT_PATH: Any
DENSENET201_WEIGHT_PATH_NO_TOP: Any

def dense_block(x: Any, blocks: Any, name: Any): ...
def transition_block(x: Any, reduction: Any, name: Any): ...
def conv_block(x: Any, growth_rate: Any, name: Any): ...
def DenseNet(blocks: Any, include_top: bool = ..., weights: str = ..., input_tensor: Optional[Any] = ..., input_shape: Optional[Any] = ..., pooling: Optional[Any] = ..., classes: int = ..., classifier_activation: str = ...): ...
def DenseNet121(include_top: bool = ..., weights: str = ..., input_tensor: Optional[Any] = ..., input_shape: Optional[Any] = ..., pooling: Optional[Any] = ..., classes: int = ...): ...
def DenseNet169(include_top: bool = ..., weights: str = ..., input_tensor: Optional[Any] = ..., input_shape: Optional[Any] = ..., pooling: Optional[Any] = ..., classes: int = ...): ...
def DenseNet201(include_top: bool = ..., weights: str = ..., input_tensor: Optional[Any] = ..., input_shape: Optional[Any] = ..., pooling: Optional[Any] = ..., classes: int = ...): ...
def preprocess_input(x: Any, data_format: Optional[Any] = ...): ...
def decode_predictions(preds: Any, top: int = ...): ...

DOC: str
