from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any

VERBOSITY_VAR_NAME: str
DEFAULT_VERBOSITY: int
verbosity_level: Any
echo_log_to_stdout: bool

def set_verbosity(level: Any, alsologtostdout: bool = ...) -> None: ...
def trace(*args: Any) -> None: ...
def get_verbosity(): ...
def has_verbosity(level: Any): ...
def error(level: Any, msg: Any, *args: Any, **kwargs: Any) -> None: ...
def log(level: Any, msg: Any, *args: Any, **kwargs: Any) -> None: ...
def warn(msg: Any, *args: Any, **kwargs: Any) -> None: ...
