from tensorflow.python.framework import ops as ops
from tensorflow.python.ops import array_ops as array_ops, gen_math_ops as gen_math_ops, math_ops as math_ops
from typing import Any

def alias_tensors(*args: Any): ...
def capitalize_initial(s: Any): ...
def get_range_len(start: Any, limit: Any, delta: Any): ...
