from tensorflow.python.autograph.pyct import anno as anno, qual_names as qual_names, transformer as transformer
from tensorflow.python.autograph.pyct.static_analysis.annos import NodeAnno as NodeAnno
from typing import Any, Optional

class Scope:
    parent: Any = ...
    isolated: Any = ...
    isolated_names: Any = ...
    read: Any = ...
    modified: Any = ...
    deleted: Any = ...
    bound: Any = ...
    globals: Any = ...
    params: Any = ...
    is_final: bool = ...
    def __init__(self, parent: Any, isolated: bool = ...) -> None: ...
    @property
    def enclosing_scope(self): ...
    @property
    def referenced(self): ...
    @property
    def free_vars(self): ...
    def copy_from(self, other: Any) -> None: ...
    @classmethod
    def copy_of(cls, other: Any): ...
    def merge_from(self, other: Any) -> None: ...
    def finalize(self) -> None: ...
    def mark_param(self, name: Any, owner: Any) -> None: ...

class _Comprehension:
    no_root: bool = ...
    is_list_comp: bool = ...
    targets: Any = ...
    def __init__(self) -> None: ...

class _FunctionOrClass:
    node: Any = ...
    def __init__(self) -> None: ...

class ActivityAnalyzer(transformer.Base):
    scope: Any = ...
    def __init__(self, context: Any, parent_scope: Optional[Any] = ...) -> None: ...
    def visit_Import(self, node: Any): ...
    def visit_ImportFrom(self, node: Any): ...
    def visit_Global(self, node: Any): ...
    def visit_Expr(self, node: Any): ...
    def visit_Raise(self, node: Any): ...
    def visit_Return(self, node: Any): ...
    def visit_Assign(self, node: Any): ...
    def visit_AnnAssign(self, node: Any): ...
    def visit_AugAssign(self, node: Any): ...
    def visit_Delete(self, node: Any): ...
    def visit_Name(self, node: Any): ...
    def visit_alias(self, node: Any): ...
    def visit_Attribute(self, node: Any): ...
    def visit_Subscript(self, node: Any): ...
    def visit_Print(self, node: Any): ...
    def visit_Assert(self, node: Any): ...
    def visit_Call(self, node: Any): ...
    def visit_comprehension(self, node: Any): ...
    def visit_DictComp(self, node: Any): ...
    def visit_ListComp(self, node: Any): ...
    def visit_SetComp(self, node: Any): ...
    def visit_GeneratorExp(self, node: Any): ...
    def visit_arguments(self, node: Any): ...
    def visit_ClassDef(self, node: Any): ...
    def visit_FunctionDef(self, node: Any): ...
    def visit_Lambda(self, node: Any): ...
    def visit_With(self, node: Any): ...
    def visit_withitem(self, node: Any): ...
    def visit_If(self, node: Any): ...
    def visit_For(self, node: Any): ...
    def visit_While(self, node: Any): ...
    def visit_ExceptHandler(self, node: Any): ...

def resolve(node: Any, context: Any, parent_scope: Optional[Any] = ...): ...
