from typing import Any

DESCRIPTOR: Any
Code: Any
OK: int
CANCELLED: int
UNKNOWN: int
INVALID_ARGUMENT: int
DEADLINE_EXCEEDED: int
NOT_FOUND: int
ALREADY_EXISTS: int
PERMISSION_DENIED: int
UNAUTHENTICATED: int
RESOURCE_EXHAUSTED: int
FAILED_PRECONDITION: int
ABORTED: int
OUT_OF_RANGE: int
UNIMPLEMENTED: int
INTERNAL: int
UNAVAILABLE: int
DATA_LOSS: int
DO_NOT_USE_RESERVED_FOR_FUTURE_EXPANSION_USE_DEFAULT_IN_SWITCH_INSTEAD_: int
