from tensorflow.python.framework import dtypes as dtypes, sparse_tensor as sparse_tensor, tensor_shape as tensor_shape
from tensorflow.python.keras.engine.base_layer import Layer as Layer
from tensorflow.python.ops import array_ops as array_ops, sparse_ops as sparse_ops
from tensorflow.python.ops.ragged import ragged_tensor as ragged_tensor
from typing import Any, Optional

class CategoryCrossing(Layer):
    depth: Any = ...
    num_bins: Any = ...
    hash_key: Any = ...
    def __init__(self, depth: Optional[Any] = ..., num_bins: Optional[Any] = ..., hash_key: Optional[Any] = ..., name: Optional[Any] = ..., **kwargs: Any) -> None: ...
    def partial_crossing(self, partial_inputs: Any, ragged_out: Any, sparse_out: Any): ...
    def call(self, inputs: Any): ...
    def compute_output_shape(self, input_shape: Any): ...
    def compute_output_signature(self, input_spec: Any): ...
    def get_config(self): ...
