from tensorflow.python.framework import dtypes as dtypes, tensor_shape as tensor_shape, tensor_spec as tensor_spec
from tensorflow.python.keras.engine.base_layer import Layer as Layer
from tensorflow.python.ops import array_ops as array_ops, math_ops as math_ops
from tensorflow.python.ops.ragged import ragged_functional_ops as ragged_functional_ops, ragged_tensor as ragged_tensor
from typing import Any

INTEGER: str
BINARY: str

class Discretization(Layer):
    bins: Any = ...
    output_mode: Any = ...
    def __init__(self, bins: Any, output_mode: Any = ..., **kwargs: Any) -> None: ...
    def get_config(self): ...
    def compute_output_shape(self, input_shape: Any): ...
    def compute_output_signature(self, input_spec: Any): ...
    def call(self, inputs: Any): ...
