from typing import Any

class ProfileAnalysisStub:
    NewSession: Any = ...
    EnumSessions: Any = ...
    GetSessionToolData: Any = ...
    def __init__(self, channel: Any) -> None: ...

class ProfileAnalysisServicer:
    def NewSession(self, request: Any, context: Any) -> None: ...
    def EnumSessions(self, request: Any, context: Any) -> None: ...
    def GetSessionToolData(self, request: Any, context: Any) -> None: ...

def add_ProfileAnalysisServicer_to_server(servicer: Any, server: Any) -> None: ...
