from tensorflow.python.platform import app as app, flags as flags
from tensorflow.python.training import py_checkpoint_reader as py_checkpoint_reader
from typing import Any

FLAGS: Any

def print_tensors_in_checkpoint_file(file_name: Any, tensor_name: Any, all_tensors: Any, all_tensor_names: bool = ..., count_exclude_pattern: str = ...) -> None: ...
def parse_numpy_printoption(kv_str: Any) -> None: ...
def main(unused_argv: Any) -> None: ...
