import enum
from typing import Any

class NoValue(enum.Enum): ...

class Basic(NoValue):
    QN: str = ...
    SKIP_PROCESSING: str = ...
    INDENT_BLOCK_REMAINDER: str = ...
    ORIGIN: str = ...
    DIRECTIVES: str = ...
    EXTRA_LOOP_TEST: str = ...

class Static(NoValue):
    IS_PARAM: str = ...
    SCOPE: str = ...
    ARGS_SCOPE: str = ...
    COND_SCOPE: str = ...
    BODY_SCOPE: str = ...
    ORELSE_SCOPE: str = ...
    DEFINITIONS: str = ...
    ORIG_DEFINITIONS: str = ...
    DEFINED_VARS_IN: str = ...
    LIVE_VARS_OUT: str = ...
    LIVE_VARS_IN: str = ...

FAIL: Any

def keys(node: Any, field_name: str = ...): ...
def getanno(node: Any, key: Any, default: Any = ..., field_name: str = ...): ...
def hasanno(node: Any, key: Any, field_name: str = ...): ...
def setanno(node: Any, key: Any, value: Any, field_name: str = ...) -> None: ...
def delanno(node: Any, key: Any, field_name: str = ...) -> None: ...
def copyanno(from_node: Any, to_node: Any, key: Any, field_name: str = ...) -> None: ...
def dup(node: Any, copy_map: Any, field_name: str = ...) -> None: ...
