from tensorflow.python.autograph.pyct import origin_info as origin_info
from typing import Any

class FrameInfo: ...

KNOWN_STRING_CONSTRUCTOR_ERRORS: Any

class MultilineMessageKeyError(KeyError):
    def __init__(self, message: Any, original_key: Any) -> None: ...

class ErrorMetadataBase:
    translated_stack: Any = ...
    cause_message: Any = ...
    def __init__(self, callsite_tb: Any, cause_metadata: Any, cause_message: Any, source_map: Any, converter_filename: Any) -> None: ...
    def get_message(self): ...
    def create_exception(self, source_error: Any): ...
    def to_exception(self, source_error: Any): ...
