import gast
from tensorflow.python.autograph.pyct import anno as anno, ast_util as ast_util, parser as parser, pretty_printer as pretty_printer
from tensorflow.python.util import tf_inspect as tf_inspect
from typing import Any

class LineLocation: ...

class Location:
    @property
    def line_loc(self): ...

class OriginInfo:
    def as_frame(self): ...

def create_source_map(nodes: Any, code: Any, filepath: Any): ...

class _Function:
    name: Any = ...
    def __init__(self, name: Any) -> None: ...

class OriginResolver(gast.NodeVisitor):
    def __init__(self, root_node: Any, source_lines: Any, comments_map: Any, context_lineno: Any, context_col_offset: Any, filepath: Any) -> None: ...
    def visit(self, node: Any) -> None: ...

def resolve(node: Any, source: Any, context_filepath: Any, context_lineno: Any, context_col_offset: Any) -> None: ...
def resolve_entity(node: Any, source: Any, entity: Any) -> None: ...
