from tensorflow.python.autograph.pyct import errors as errors, inspect_utils as inspect_utils
from typing import Any, Optional

STANDARD_PREAMBLE: Any
STANDARD_PREAMBLE_LEN: int

def dedent_block(code_string: Any): ...
def parse_entity(entity: Any, future_features: Any): ...
def parse(src: Any, preamble_len: int = ..., single_node: bool = ...): ...
def parse_expression(src: Any): ...
def unparse(node: Any, indentation: Optional[Any] = ..., include_encoding_marker: bool = ...): ...
