import gast
from tensorflow.python.autograph.pyct import anno as anno, ast_util as ast_util, parser as parser, qual_names as qual_names
from typing import Any

class ContextAdjuster(gast.NodeTransformer):
    def __init__(self, override_value: Any) -> None: ...
    def visit(self, node: Any): ...
    def visit_Attribute(self, node: Any): ...
    def visit_Tuple(self, node: Any): ...
    def visit_List(self, node: Any): ...
    def visit_Name(self, node: Any): ...
    def visit_Call(self, node: Any): ...
    def visit_Dict(self, node: Any): ...
    def visit_Subscript(self, node: Any): ...
    def visit_comprehension(self, node: Any): ...
    def visit_Lambda(self, node: Any): ...

class ReplaceTransformer(gast.NodeTransformer):
    replacements: Any = ...
    in_replacements: bool = ...
    preserved_annos: Any = ...
    def __init__(self, replacements: Any) -> None: ...
    def visit_Expr(self, node: Any): ...
    def visit_keyword(self, node: Any): ...
    def visit_FunctionDef(self, node: Any): ...
    def visit_Attribute(self, node: Any): ...
    def visit_Name(self, node: Any): ...

def replace(template: Any, **replacements: Any): ...
def replace_as_expression(template: Any, **replacements: Any): ...
