from tensorflow.python import pywrap_tfe as pywrap_tfe
from typing import Any, Optional

class TangentInfo:
    def __new__(cls, indices: Optional[Any] = ..., tangents: Optional[Any] = ...): ...

def pack_tangents(tensors: Any): ...
def push_forwardprop_state() -> None: ...
