from typing import Any

def start_tracing(service_addr: Any, logdir: Any, duration_ms: Any, worker_list: str = ..., include_dataset_ops: bool = ..., num_tracing_attempts: int = ...) -> None: ...
def monitor(service_addr: Any, duration_ms: Any, monitoring_level: int = ..., display_timestamp: bool = ...): ...
