from tensorflow.python.eager import context as context
from tensorflow.python.framework import errors as errors
from tensorflow.python.platform import gfile as gfile
from tensorflow.python.util import compat as compat
from typing import Any

class ProfilerAlreadyRunningError(Exception): ...
class ProfilerNotRunningError(Exception): ...

def start() -> None: ...
def stop(): ...
def maybe_create_event_file(logdir: Any) -> None: ...
def save(logdir: Any, result: Any) -> None: ...
def start_profiler_server(port: Any) -> None: ...

class Profiler:
    def __init__(self, logdir: Any) -> None: ...
    def __enter__(self) -> None: ...
    def __exit__(self, typ: Any, value: Any, tb: Any) -> None: ...
