from tensorflow.python.framework import constant_op as constant_op, dtypes as dtypes, ops as ops, tensor_util as tensor_util
from tensorflow.python.ops import array_ops as array_ops, math_ops as math_ops
from tensorflow.python.ops.signal import dct_ops as dct_ops, fft_ops as fft_ops, reconstruction_ops as reconstruction_ops, shape_ops as shape_ops, window_ops as window_ops
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any, Optional

def stft(signals: Any, frame_length: Any, frame_step: Any, fft_length: Optional[Any] = ..., window_fn: Any = ..., pad_end: bool = ..., name: Optional[Any] = ...): ...
def inverse_stft_window_fn(frame_step: Any, forward_window_fn: Any = ..., name: Optional[Any] = ...): ...
def inverse_stft(stfts: Any, frame_length: Any, frame_step: Any, fft_length: Optional[Any] = ..., window_fn: Any = ..., name: Optional[Any] = ...): ...
def mdct(signals: Any, frame_length: Any, window_fn: Any = ..., pad_end: bool = ..., norm: Optional[Any] = ..., name: Optional[Any] = ...): ...
def inverse_mdct(mdcts: Any, window_fn: Any = ..., norm: Optional[Any] = ..., name: Optional[Any] = ...): ...
