from tensorflow.python.framework import constant_op as constant_op, dtypes as dtypes, ops as ops, tensor_util as tensor_util
from tensorflow.python.ops import array_ops as array_ops, control_flow_ops as control_flow_ops, math_ops as math_ops
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any, Optional

def kaiser_window(window_length: Any, beta: float = ..., dtype: Any = ..., name: Optional[Any] = ...): ...
def kaiser_bessel_derived_window(window_length: Any, beta: float = ..., dtype: Any = ..., name: Optional[Any] = ...): ...
def vorbis_window(window_length: Any, dtype: Any = ..., name: Optional[Any] = ...): ...
def hann_window(window_length: Any, periodic: bool = ..., dtype: Any = ..., name: Optional[Any] = ...): ...
def hamming_window(window_length: Any, periodic: bool = ..., dtype: Any = ..., name: Optional[Any] = ...): ...
