from typing import Any

class ReductionV2:
    AUTO: str = ...
    NONE: str = ...
    SUM: str = ...
    SUM_OVER_BATCH_SIZE: str = ...
    @classmethod
    def all(cls): ...
    @classmethod
    def validate(cls, key: Any) -> None: ...
