from typing import Any

def CalibrationWrapper_Calibrate(*args, **kwargs) -> Any: ...
def CalibrationWrapper_CreateWrapperCPPFromBuffer(*args, **kwargs) -> Any: ...
def CalibrationWrapper_FeedTensor(*args, **kwargs) -> Any: ...
def CalibrationWrapper_Prepare(*args, **kwargs) -> Any: ...
def CalibrationWrapper_QuantizeModel(*args, **kwargs) -> Any: ...
def CalibrationWrapper_swigregister(*args, **kwargs) -> Any: ...
def SWIG_PyInstanceMethod_New(*args, **kwargs) -> Any: ...
def delete_CalibrationWrapper(*args, **kwargs) -> Any: ...
