from tensorflow.python.util.lazy_loader import LazyLoader as LazyLoader
from typing import Any

class Calibrator:
    def __init__(self, model_content: Any) -> None: ...
    def calibrate_and_quantize(self, dataset_gen: Any, input_type: Any, output_type: Any, allow_float: Any, enable_mlir_quantizer: bool = ...): ...
    def calibrate_and_quantize_single(self, dataset_gen: Any, input_type: Any, output_type: Any, allow_float: Any, op_output_name: Any): ...
    def calibrate(self, dataset_gen: Any): ...
