from typing import Any

def swig_import_helper(): ...

class _object: ...

class CalibrationWrapper(_object):
    __swig_setmethods__: Any = ...
    __setattr__: Any = ...
    __swig_getmethods__: Any = ...
    __getattr__: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    CreateWrapperCPPFromBuffer: Any = ...
    __swig_destroy__: Any = ...
    __del__: Any = ...
    def Prepare(self): ...
    def FeedTensor(self, input_value: Any): ...
    def QuantizeModel(self, *args: Any): ...
    def Calibrate(self): ...

CalibrationWrapper_swigregister: Any

def CalibrationWrapper_CreateWrapperCPPFromBuffer(data: Any): ...

CalibrationWrapper_CreateWrapperCPPFromBuffer: Any
