from tensorflow.python.ops import init_ops as init_ops
from tensorflow.python.util.lazy_loader import LazyLoader as LazyLoader
from typing import Any, Optional

generic_utils: Any

def serialize_feature_column(fc: Any): ...
def deserialize_feature_column(config: Any, custom_objects: Optional[Any] = ..., columns_by_name: Optional[Any] = ...): ...
def serialize_feature_columns(feature_columns: Any): ...
def deserialize_feature_columns(configs: Any, custom_objects: Optional[Any] = ...): ...
