from typing import Any, Optional

def make_all(module_name: Any, doc_string_modules: Optional[Any] = ...): ...
def reveal_undocumented(symbol_name: Any, target_module: Optional[Any] = ...) -> None: ...
def remove_undocumented(module_name: Any, allowed_exception_list: Optional[Any] = ..., doc_string_modules: Optional[Any] = ...) -> None: ...
