from tensorflow.python.util import tf_decorator as tf_decorator, tf_inspect as tf_inspect
from typing import Any

DISPATCH_ATTR: str

class OpDispatcher:
    NOT_SUPPORTED: Any = ...
    def handle(self, args: Any, kwargs: Any): ...
    def register(self, op: Any) -> None: ...

def dispatch(op: Any, *args: Any, **kwargs: Any): ...

class _TypeBasedDispatcher(OpDispatcher):
    def __init__(self, override_func: Any, types: Any) -> None: ...
    def handle(self, args: Any, kwargs: Any): ...

def dispatch_for_types(op: Any, *types: Any): ...
def add_dispatch_list(target: Any): ...
def add_dispatch_support(target: Any): ...
