from tensorflow.core.protobuf import config_pb2 as config_pb2
from tensorflow.python.util import tf_decorator as tf_decorator, tf_inspect as tf_inspect
from typing import Any

def fn_args(fn: Any): ...
def has_kwargs(fn: Any): ...
def get_func_name(func: Any): ...
def get_func_code(func: Any): ...
def get_disabled_rewriter_config(): ...
