import types
from typing import Any, Optional

class LazyLoader(types.ModuleType):
    def __init__(self, local_name: Any, parent_module_globals: Any, name: Any, warning: Optional[Any] = ...) -> None: ...
    def __getattr__(self, item: Any): ...
    def __dir__(self): ...
