import types
from tensorflow.python.util import tf_decorator as tf_decorator, tf_inspect as tf_inspect, tf_stack as tf_stack
from tensorflow.tools.compatibility import all_renames_v2 as all_renames_v2
from typing import Any, Optional

def get_rename_v2(name: Any): ...
def contains_deprecation_decorator(decorators: Any): ...
def has_deprecation_decorator(symbol: Any): ...

class TFModuleWrapper(types.ModuleType):
    def __init__(self, wrapped: Any, module_name: Any, public_apis: Optional[Any] = ..., deprecation: bool = ..., has_lite: bool = ...) -> None: ...
    def __getattribute__(self, name: Any): ...
    def __getattr__(self, name: Any): ...
    def __setattr__(self, arg: Any, val: Any) -> None: ...
    def __dir__(self): ...
    def __delattr__(self, name: Any) -> None: ...
    def __reduce__(self): ...
