from tensorflow.python.util.compat import collections_abc as collections_abc
from typing import Any

class _ObjectIdentityWrapper:
    def __init__(self, wrapped: Any) -> None: ...
    @property
    def unwrapped(self): ...
    def __lt__(self, other: Any) -> Any: ...
    def __gt__(self, other: Any) -> Any: ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
    def __hash__(self) -> Any: ...

class _WeakObjectIdentityWrapper(_ObjectIdentityWrapper):
    def __init__(self, wrapped: Any) -> None: ...
    @property
    def unwrapped(self): ...

class Reference(_ObjectIdentityWrapper):
    unwrapped: Any = ...
    def deref(self): ...

class ObjectIdentityDictionary(collections_abc.MutableMapping):
    def __init__(self) -> None: ...
    def __getitem__(self, key: Any): ...
    def __setitem__(self, key: Any, value: Any) -> None: ...
    def __delitem__(self, key: Any) -> None: ...
    def __len__(self): ...
    def __iter__(self) -> Any: ...

class ObjectIdentityWeakKeyDictionary(ObjectIdentityDictionary):
    def __len__(self): ...
    def __iter__(self) -> Any: ...

class ObjectIdentitySet(collections_abc.MutableSet):
    def __init__(self, *args: Any) -> None: ...
    def __contains__(self, key: Any): ...
    def discard(self, key: Any) -> None: ...
    def add(self, key: Any) -> None: ...
    def update(self, items: Any) -> None: ...
    def clear(self) -> None: ...
    def intersection(self, items: Any): ...
    def difference(self, items: Any): ...
    def __len__(self): ...
    def __iter__(self) -> Any: ...

class ObjectIdentityWeakSet(ObjectIdentitySet):
    def __len__(self): ...
    def __iter__(self) -> Any: ...
