from typing import Any

class StackTraceTransform:
    parent: Any = ...
    def __enter__(self): ...
    def __exit__(self, unused_type: Any, unused_value: Any, unused_traceback: Any) -> None: ...
    def reset(self) -> None: ...

class StackTraceMapper(StackTraceTransform):
    def reset(self) -> None: ...
    def get_effective_source_map(self) -> None: ...

class StackTraceFilter(StackTraceTransform):
    def reset(self) -> None: ...
    def get_filtered_filenames(self) -> None: ...

class CurrentModuleFilter(StackTraceFilter):
    def __init__(self) -> None: ...
    def get_filtered_filenames(self): ...

def extract_stack(limit: int = ...): ...

StackSummary: Any
FrameSummary: Any
