from tensorflow.core.framework.graph_pb2 import *
from tensorflow.core.framework.node_def_pb2 import *
from tensorflow.core.framework.summary_pb2 import *
from tensorflow.core.framework.attr_value_pb2 import *
from tensorflow.core.protobuf.config_pb2 import *
from tensorflow.core.protobuf.tensorflow_server_pb2 import *
from tensorflow.core.util.event_pb2 import *
from tensorflow.python.framework.framework_lib import *
from tensorflow.python.framework.versions import *
from tensorflow.python.client.client_lib import *
from tensorflow.python.ops.standard_ops import *
import ctypes as ctypes
import importlib as importlib
import numpy as np
import sys as sys
import traceback as traceback
from tensorflow.core.protobuf.meta_graph_pb2 import MetaGraphDef as MetaGraphDef, TensorInfo as TensorInfo
from tensorflow.python import data as data, distribute as distribute, keras as keras, pywrap_tensorflow as pywrap_tensorflow
from tensorflow.python.compat import v2_compat as v2_compat
from tensorflow.python.compiler.mlir import mlir as mlir
from tensorflow.python.compiler.xla import jit as jit, xla as xla
from tensorflow.python.debug.lib import check_numerics_callback as check_numerics_callback, dumping_callback as dumping_callback
from tensorflow.python.dlpack.dlpack import from_dlpack as from_dlpack, to_dlpack as to_dlpack
from tensorflow.python.eager.context import executing_eagerly as executing_eagerly
from tensorflow.python.eager.def_function import function as function
from tensorflow.python.eager.remote import connect_to_remote_host as connect_to_remote_host
from tensorflow.python.feature_column import feature_column_lib as feature_column
from tensorflow.python.framework import config as config, errors as errors, graph_util as graph_util
from tensorflow.python.framework.ops import enable_eager_execution as enable_eager_execution
from tensorflow.python.layers import layers as layers
from tensorflow.python.lib.io import python_io as python_io
from tensorflow.python.module import module as module
from tensorflow.python.ops import bitwise_ops as bitwise, gen_audio_ops as gen_audio_ops, gen_boosted_trees_ops as gen_boosted_trees_ops, gen_cudnn_rnn_ops as gen_cudnn_rnn_ops, gen_debug_ops as gen_debug_ops, gen_rnn_ops as gen_rnn_ops, gen_sendrecv_ops as gen_sendrecv_ops, gradient_checker_v2 as gradient_checker_v2, image_ops as image, initializers_ns as initializers, manip_ops as manip, metrics as metrics, nn as nn, ragged as ragged, rnn as rnn, rnn_cell as rnn_cell, sets as sets, stateful_random_ops as stateful_random_ops
from tensorflow.python.ops.distributions import distributions as distributions
from tensorflow.python.ops.linalg import linalg as linalg
from tensorflow.python.ops.linalg.sparse import sparse as sparse
from tensorflow.python.ops.losses import losses as losses
from tensorflow.python.ops.signal import signal as signal
from tensorflow.python.platform import app as app, flags as flags, gfile as gfile, resource_loader as resource_loader, sysconfig as sysconfig, test as test, tf_logging as logging
from tensorflow.python.profiler import profiler as profiler, profiler_client as profiler_client, profiler_v2 as profiler_v2
from tensorflow.python.saved_model import saved_model as saved_model
from tensorflow.python.summary import summary as summary
from tensorflow.python.tpu import api as api
from tensorflow.python.training import training as train
from tensorflow.python.user_ops import user_ops as user_ops
from tensorflow.python.util import compat as compat
from tensorflow.python.util.all_util import make_all as make_all
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any as Any

# Names in __all__ with no definition:
#   AUTO_REUSE
#   Abs
#   AccumulateNV2
#   AccumulatorApplyGradient
#   AccumulatorNumAccumulated
#   AccumulatorSetGlobalStep
#   AccumulatorTakeGradient
#   Acos
#   Acosh
#   Add
#   AddManySparseToTensorsMap
#   AddN
#   AddSparseToTensorsMap
#   AddV2
#   AggregationMethod
#   All
#   Angle
#   Any
#   ApproximateEqual
#   ArgMax
#   ArgMin
#   AsString
#   Asin
#   Asinh
#   Assert
#   Atan
#   Atan2
#   Atanh
#   AttrValue
#   Barrier
#   BarrierClose
#   BarrierIncompleteSize
#   BarrierInsertMany
#   BarrierReadySize
#   BarrierTakeMany
#   BaseStagingArea
#   Batch
#   BatchCholesky
#   BatchCholeskyGrad
#   BatchFunction
#   BatchMatMul
#   BatchMatMulV2
#   BatchMatrixBandPart
#   BatchMatrixDeterminant
#   BatchMatrixDiag
#   BatchMatrixDiagPart
#   BatchMatrixInverse
#   BatchMatrixSetDiag
#   BatchMatrixSolve
#   BatchMatrixSolveLs
#   BatchMatrixTriangularSolve
#   BatchSelfAdjointEig
#   BatchSelfAdjointEigV2
#   BatchSvd
#   BatchToSpace
#   BatchToSpaceND
#   BesselI0e
#   BesselI1e
#   Betainc
#   Bincount
#   Bitcast
#   BroadcastArgs
#   BroadcastGradientArgs
#   BroadcastTo
#   Bucketize
#   COMPILER_VERSION
#   CXX11_ABI_FLAG
#   CallableOptions
#   Cast
#   Ceil
#   CheckNumerics
#   CheckNumericsV2
#   Cholesky
#   CholeskyGrad
#   ClipByValue
#   CompareAndBitpack
#   Complex
#   ComplexAbs
#   Concat
#   ConcatOffset
#   ConcatV2
#   ConditionalAccumulator
#   ConditionalAccumulatorBase
#   ConfigProto
#   Conj
#   ConjugateTranspose
#   Const
#   Constant
#   ConvolutionDeltaOrthogonal
#   ConvolutionOrthogonal
#   ConvolutionOrthogonal1D
#   ConvolutionOrthogonal2D
#   ConvolutionOrthogonal3D
#   Cos
#   Cosh
#   CriticalSection
#   Cross
#   Cumprod
#   Cumsum
#   CumulativeLogsumexp
#   DATA_CLASS_BLOB_SEQUENCE
#   DATA_CLASS_SCALAR
#   DATA_CLASS_TENSOR
#   DATA_CLASS_UNKNOWN
#   DEFAULT
#   DESCRIPTOR
#   DType
#   DataClass
#   DebugGradientIdentity
#   DebugGradientRefIdentity
#   DecodeBase64
#   DecodeCSV
#   DecodeCompressed
#   DecodeJSONExample
#   DecodePaddedRaw
#   DecodeRaw
#   DeepCopy
#   DeleteSessionTensor
#   DepthToSpace
#   Dequantize
#   DeserializeManySparse
#   DeserializeSparse
#   DeviceSpec
#   Diag
#   DiagPart
#   Digamma
#   Dimension
#   Div
#   DivNoNan
#   DivideDelegateWithName
#   DynamicPartition
#   DynamicStitch
#   EditDistance
#   Eig
#   Einsum
#   Empty
#   EncodeBase64
#   EnsureShape
#   Equal
#   Erf
#   Erfc
#   Erfinv
#   EuclideanNorm
#   Event
#   Exp
#   ExpandDims
#   Expm1
#   ExtractImagePatches
#   ExtractVolumePatches
#   FIFOQueue
#   FIFOQueueV2
#   FakeQuantWithMinMaxArgs
#   FakeQuantWithMinMaxArgsGradient
#   FakeQuantWithMinMaxVars
#   FakeQuantWithMinMaxVarsGradient
#   FakeQuantWithMinMaxVarsPerChannel
#   FakeQuantWithMinMaxVarsPerChannelGradient
#   FakeQueue
#   Fill
#   Fingerprint
#   FixedLenFeature
#   FixedLenSequenceFeature
#   FixedLengthRecordReader
#   FixedLengthRecordReaderV2
#   Floor
#   FloorDiv
#   FloorMod
#   For
#   ForwardAccumulator
#   GIT_VERSION
#   GPUCompatibleFIFOQueue
#   GPUOptions
#   GRAPH_DEF_VERSION
#   GRAPH_DEF_VERSION_MIN_CONSUMER
#   GRAPH_DEF_VERSION_MIN_PRODUCER
#   Gather
#   GatherNd
#   GatherV2
#   GetSessionHandle
#   GetSessionHandleV2
#   GetSessionTensor
#   GlorotNormal
#   GlorotUniform
#   Gradient
#   GradientTape
#   Graph
#   GraphDef
#   GraphKeys
#   GraphOptions
#   Greater
#   GreaterEqual
#   GuaranteeConst
#   HistogramFixedWidth
#   HistogramProto
#   INTERNAL_ERROR
#   Identity
#   IdentityN
#   IdentityReader
#   IdentityReaderV2
#   If
#   Igamma
#   IgammaGradA
#   Igammac
#   Imag
#   ImmutableConst
#   IndexedSlices
#   Initializer
#   InplaceAdd
#   InplaceSub
#   InplaceUpdate
#   InteractiveSession
#   Inv
#   InvGrad
#   InvertPermutation
#   IsFinite
#   IsInf
#   IsNan
#   KeywordRequired
#   LMDBReader
#   Less
#   LessEqual
#   Lgamma
#   LinSpace
#   ListDiff
#   Log
#   Log1p
#   LogMatrixDeterminant
#   LogMessage
#   LogicalAnd
#   LogicalNot
#   LogicalOr
#   LowerBound
#   Lu
#   MONOLITHIC_BUILD
#   MapClear
#   MapIncompleteSize
#   MapPeek
#   MapSize
#   MapStage
#   MapStagingArea
#   MapUnstage
#   MapUnstageNoKey
#   MatMul
#   MatchingFiles
#   MatrixBandPart
#   MatrixDeterminant
#   MatrixDiag
#   MatrixDiagPart
#   MatrixDiagPartV2
#   MatrixDiagPartV3
#   MatrixDiagV2
#   MatrixDiagV3
#   MatrixExponential
#   MatrixInverse
#   MatrixLogarithm
#   MatrixSetDiag
#   MatrixSetDiagV2
#   MatrixSetDiagV3
#   MatrixSolve
#   MatrixSolveLs
#   MatrixSquareRoot
#   MatrixTriangularSolve
#   Max
#   Maximum
#   Mean
#   MergeV2Checkpoints
#   Min
#   Minimum
#   MirrorPad
#   MirrorPadGrad
#   Mod
#   Mul
#   MulNoNan
#   Multinomial
#   NEW_AXIS
#   NOT_CONFIGURED
#   NameAttrList
#   Ndtri
#   Neg
#   NextAfter
#   NoGradient
#   NodeDef
#   NotDifferentiable
#   NotEqual
#   OK
#   OneHot
#   Ones
#   OnesLike
#   OpError
#   Operation
#   OptimizerOptions
#   OrderedMapClear
#   OrderedMapIncompleteSize
#   OrderedMapPeek
#   OrderedMapSize
#   OrderedMapStage
#   OrderedMapUnstage
#   OrderedMapUnstageNoKey
#   Orthogonal
#   Pack
#   Pad
#   PadV2
#   PaddingFIFOQueue
#   PaddingFIFOQueueV2
#   ParallelConcat
#   ParallelDynamicStitch
#   ParameterizedTruncatedNormal
#   ParseExample
#   ParseExampleV2
#   ParseSequenceExample
#   ParseSequenceExampleV2
#   ParseSingleExample
#   ParseSingleSequenceExample
#   ParseTensor
#   PartitionedVariable
#   Placeholder
#   PlaceholderV2
#   PlaceholderWithDefault
#   Polygamma
#   Pow
#   PreventGradient
#   Print
#   PriorityQueue
#   PriorityQueueV2
#   Prod
#   QUANTIZED_DTYPES
#   Qr
#   QuantizeAndDequantize
#   QuantizeAndDequantizeV2
#   QuantizeAndDequantizeV3
#   QuantizeDownAndShrinkRange
#   QuantizeV2
#   QuantizedAdd
#   QuantizedConcat
#   QuantizedInstanceNorm
#   QuantizedMatMul
#   QuantizedMul
#   QuantizedReshape
#   QueueBase
#   QueueClose
#   QueueCloseV2
#   QueueDequeue
#   QueueDequeueMany
#   QueueDequeueManyV2
#   QueueDequeueUpTo
#   QueueDequeueUpToV2
#   QueueDequeueV2
#   QueueEnqueue
#   QueueEnqueueMany
#   QueueEnqueueManyV2
#   QueueEnqueueV2
#   QueueIsClosed
#   QueueIsClosedV2
#   QueueSize
#   QueueSizeV2
#   RECEIVED_SHUTDOWN_SIGNAL
#   RPCOptions
#   RaggedFeature
#   RandomGamma
#   RandomGammaGrad
#   RandomNormal
#   RandomPoisson
#   RandomPoissonV2
#   RandomShuffle
#   RandomShuffleQueue
#   RandomShuffleQueueV2
#   RandomStandardNormal
#   RandomUniform
#   RandomUniformInt
#   Range
#   Rank
#   ReadFile
#   ReaderBase
#   ReaderNumRecordsProduced
#   ReaderNumRecordsProducedV2
#   ReaderNumWorkUnitsCompleted
#   ReaderNumWorkUnitsCompletedV2
#   ReaderRead
#   ReaderReadUpTo
#   ReaderReadUpToV2
#   ReaderReadV2
#   ReaderReset
#   ReaderResetV2
#   ReaderRestoreState
#   ReaderRestoreStateV2
#   ReaderSerializeState
#   ReaderSerializeStateV2
#   Real
#   RealDiv
#   Reciprocal
#   ReciprocalGrad
#   RecordInput
#   ReduceJoin
#   RefIdentity
#   RefVariable
#   RegexFullMatch
#   RegexReplace
#   RegisterGradient
#   RequantizationRange
#   RequantizationRangePerChannel
#   Requantize
#   RequantizePerChannel
#   RequestedExitCode
#   Reshape
#   ResourceAccumulatorApplyGradient
#   ResourceAccumulatorNumAccumulated
#   ResourceAccumulatorSetGlobalStep
#   ResourceAccumulatorTakeGradient
#   ResourceConditionalAccumulator
#   ResourceStridedSliceAssign
#   Restore
#   RestoreSlice
#   RestoreV2
#   Reverse
#   ReverseSequence
#   ReverseV2
#   Rint
#   Round
#   Rsqrt
#   RsqrtGrad
#   RunMetadata
#   RunOptions
#   SHRINK_AXIS
#   SHUTDOWN_AFTER_TIMEOUT
#   SHUTTING_DOWN
#   Save
#   SaveSlices
#   SaveV2
#   ScatterNd
#   ScatterNdNonAliasingAdd
#   SegmentMax
#   SegmentMean
#   SegmentMin
#   SegmentProd
#   SegmentSum
#   Select
#   SelectV2
#   SelfAdjointEig
#   SelfAdjointEigV2
#   SerializeManySparse
#   SerializeSparse
#   SerializeTensor
#   ServerDef
#   Session
#   SessionLog
#   SessionMetadata
#   Shape
#   ShapeN
#   ShardedFilename
#   ShardedFilespec
#   Sigmoid
#   SigmoidGrad
#   Sign
#   Sin
#   Sinh
#   Size
#   Slice
#   Snapshot
#   SobolSample
#   SpaceToBatch
#   SpaceToBatchND
#   SpaceToDepth
#   SparseAccumulatorApplyGradient
#   SparseAccumulatorTakeGradient
#   SparseAdd
#   SparseAddGrad
#   SparseConcat
#   SparseConditionalAccumulator
#   SparseCross
#   SparseDenseCwiseAdd
#   SparseDenseCwiseDiv
#   SparseDenseCwiseMul
#   SparseFeature
#   SparseFillEmptyRows
#   SparseFillEmptyRowsGrad
#   SparseMatMul
#   SparseReduceMax
#   SparseReduceMaxSparse
#   SparseReduceSum
#   SparseReduceSumSparse
#   SparseReorder
#   SparseReshape
#   SparseSegmentMean
#   SparseSegmentMeanGrad
#   SparseSegmentMeanWithNumSegments
#   SparseSegmentSqrtN
#   SparseSegmentSqrtNGrad
#   SparseSegmentSqrtNWithNumSegments
#   SparseSegmentSum
#   SparseSegmentSumWithNumSegments
#   SparseSlice
#   SparseSliceGrad
#   SparseSoftmax
#   SparseSparseMaximum
#   SparseSparseMinimum
#   SparseSplit
#   SparseTensor
#   SparseTensorDenseAdd
#   SparseTensorDenseMatMul
#   SparseTensorValue
#   SparseToDense
#   Split
#   SplitV
#   Sqrt
#   SqrtGrad
#   Square
#   SquaredDifference
#   Squeeze
#   Stack
#   StackClose
#   StackCloseV2
#   StackPop
#   StackPopV2
#   StackPush
#   StackPushV2
#   StackV2
#   Stage
#   StageClear
#   StagePeek
#   StageSize
#   StagingArea
#   StaticRegexFullMatch
#   StaticRegexReplace
#   StopGradient
#   StridedSlice
#   StridedSliceAssign
#   StridedSliceGrad
#   StringFormat
#   StringJoin
#   StringLength
#   StringLower
#   StringNGrams
#   StringSplit
#   StringSplitV2
#   StringStrip
#   StringToHashBucket
#   StringToHashBucketFast
#   StringToHashBucketStrong
#   StringToNumber
#   StringUpper
#   Sub
#   Substr
#   Sum
#   Summary
#   SummaryDescription
#   SummaryMetadata
#   Svd
#   TFRecordReader
#   TFRecordReaderV2
#   TF_VALUE_DTYPES
#   TaggedRunMetadata
#   TakeManySparseFromTensorsMap
#   Tan
#   Tanh
#   TanhGrad
#   Tensor
#   TensorArray
#   TensorArrayClose
#   TensorArrayCloseV2
#   TensorArrayCloseV3
#   TensorArrayConcat
#   TensorArrayConcatV2
#   TensorArrayConcatV3
#   TensorArrayGather
#   TensorArrayGatherV2
#   TensorArrayGatherV3
#   TensorArrayGrad
#   TensorArrayGradV2
#   TensorArrayGradV3
#   TensorArrayGradWithShape
#   TensorArrayPack
#   TensorArrayRead
#   TensorArrayReadV2
#   TensorArrayReadV3
#   TensorArrayScatter
#   TensorArrayScatterV2
#   TensorArrayScatterV3
#   TensorArraySize
#   TensorArraySizeV2
#   TensorArraySizeV3
#   TensorArraySpec
#   TensorArraySplit
#   TensorArraySplitV2
#   TensorArraySplitV3
#   TensorArrayUnpack
#   TensorArrayV2
#   TensorArrayV3
#   TensorArrayWrite
#   TensorArrayWriteV2
#   TensorArrayWriteV3
#   TensorConnection
#   TensorHandle
#   TensorScatterAdd
#   TensorScatterSub
#   TensorScatterUpdate
#   TensorShape
#   TensorStridedSliceUpdate
#   TextLineReader
#   TextLineReaderV2
#   ThreadPoolOptionProto
#   Tile
#   TileGrad
#   Transpose
#   TridiagonalMatMul
#   TridiagonalSolve
#   TruncateDiv
#   TruncateMod
#   TruncatedNormal
#   Unbatch
#   UnbatchGrad
#   UnconnectedGradients
#   UnicodeDecode
#   UnicodeDecodeWithOffsets
#   UnicodeEncode
#   UnicodeScript
#   UnicodeTranscode
#   UniformUnitScaling
#   Unique
#   UniqueV2
#   UniqueWithCounts
#   UniqueWithCountsV2
#   Unpack
#   UnravelIndex
#   UnsortedSegmentJoin
#   UnsortedSegmentMax
#   UnsortedSegmentMin
#   UnsortedSegmentProd
#   UnsortedSegmentSum
#   Unstage
#   UpperBound
#   VERSION
#   VarLenFeature
#   Variable
#   VariableAggregation
#   VariableAggregationV2
#   VariableMetaclass
#   VariableScope
#   VariableSynchronization
#   VariableV1
#   VarianceScaling
#   WAIT_FOR_COORDINATOR
#   WatchdogConfig
#   Where
#   While
#   WholeFileReader
#   WholeFileReaderV2
#   WorkerHealth
#   WorkerHeartbeatRequest
#   WorkerHeartbeatResponse
#   WorkerShutdownMode
#   WriteFile
#   Xdivy
#   Xlog1py
#   Xlogy
#   Zeros
#   ZerosLike
#   Zeta
#   __compiler_version__
#   __cxx11_abi_flag__
#   __git_version__
#   __monolithic_build__
#   __version__
#   abs
#   absolute_import
#   accumulate_n
#   accumulate_nv2
#   accumulate_nv2_eager_fallback
#   accumulator_apply_gradient
#   accumulator_apply_gradient_eager_fallback
#   accumulator_num_accumulated
#   accumulator_num_accumulated_eager_fallback
#   accumulator_set_global_step
#   accumulator_set_global_step_eager_fallback
#   accumulator_take_gradient
#   accumulator_take_gradient_eager_fallback
#   acd
#   acos
#   acos_eager_fallback
#   acosh
#   acosh_eager_fallback
#   add
#   add_check_numerics_ops
#   add_eager_fallback
#   add_many_sparse_to_tensors_map
#   add_many_sparse_to_tensors_map_eager_fallback
#   add_n
#   add_n_eager_fallback
#   add_sparse_to_tensors_map
#   add_sparse_to_tensors_map_eager_fallback
#   add_to_collection
#   add_to_collections
#   add_v2
#   add_v2_eager_fallback
#   all_variables
#   angle
#   angle_eager_fallback
#   approximate_equal
#   approximate_equal_eager_fallback
#   arg_max
#   arg_max_eager_fallback
#   arg_min
#   arg_min_eager_fallback
#   argmax
#   argmax_v2
#   argmin
#   argmin_v2
#   argsort
#   array_grad
#   array_ops
#   as_dtype
#   as_string
#   as_string_eager_fallback
#   asin
#   asin_eager_fallback
#   asinh
#   asinh_eager_fallback
#   assert_equal
#   assert_greater
#   assert_greater_equal
#   assert_integer
#   assert_less
#   assert_less_equal
#   assert_near
#   assert_negative
#   assert_non_negative
#   assert_non_positive
#   assert_none_equal
#   assert_positive
#   assert_proper_iterable
#   assert_rank
#   assert_rank_at_least
#   assert_rank_in
#   assert_same_float_dtype
#   assert_scalar
#   assert_shapes
#   assert_type
#   assert_variables_initialized
#   assign
#   assign_add
#   assign_sub
#   atan
#   atan2
#   atan2_eager_fallback
#   atan_eager_fallback
#   atanh
#   atanh_eager_fallback
#   attr_value_pb2
#   autograph
#   barrier
#   barrier_close
#   barrier_close_eager_fallback
#   barrier_eager_fallback
#   barrier_incomplete_size
#   barrier_incomplete_size_eager_fallback
#   barrier_insert_many
#   barrier_insert_many_eager_fallback
#   barrier_ready_size
#   barrier_ready_size_eager_fallback
#   barrier_take_many
#   barrier_take_many_eager_fallback
#   batch
#   batch_cholesky
#   batch_cholesky_eager_fallback
#   batch_cholesky_grad
#   batch_cholesky_grad_eager_fallback
#   batch_eager_fallback
#   batch_function
#   batch_function_eager_fallback
#   batch_gather
#   batch_gather_nd
#   batch_mat_mul
#   batch_mat_mul_eager_fallback
#   batch_mat_mul_v2
#   batch_mat_mul_v2_eager_fallback
#   batch_matrix_band_part
#   batch_matrix_band_part_eager_fallback
#   batch_matrix_determinant
#   batch_matrix_determinant_eager_fallback
#   batch_matrix_diag
#   batch_matrix_diag_eager_fallback
#   batch_matrix_diag_part
#   batch_matrix_diag_part_eager_fallback
#   batch_matrix_inverse
#   batch_matrix_inverse_eager_fallback
#   batch_matrix_set_diag
#   batch_matrix_set_diag_eager_fallback
#   batch_matrix_solve
#   batch_matrix_solve_eager_fallback
#   batch_matrix_solve_ls
#   batch_matrix_solve_ls_eager_fallback
#   batch_matrix_triangular_solve
#   batch_matrix_triangular_solve_eager_fallback
#   batch_self_adjoint_eig
#   batch_self_adjoint_eig_eager_fallback
#   batch_self_adjoint_eig_v2
#   batch_self_adjoint_eig_v2_eager_fallback
#   batch_svd
#   batch_svd_eager_fallback
#   batch_to_space
#   batch_to_space_eager_fallback
#   batch_to_space_nd
#   batch_to_space_nd_eager_fallback
#   batch_to_space_v2
#   bessel_i0
#   bessel_i0e
#   bessel_i0e_eager_fallback
#   bessel_i1
#   bessel_i1e
#   bessel_i1e_eager_fallback
#   betainc
#   betainc_eager_fallback
#   bfloat16
#   bfloat16_ref
#   bincount
#   bincount_eager_fallback
#   bincount_v1
#   bitcast
#   bitcast_eager_fallback
#   bool
#   bool_ref
#   boolean_mask
#   boolean_mask_v2
#   broadcast_args
#   broadcast_args_eager_fallback
#   broadcast_dynamic_shape
#   broadcast_gradient_args
#   broadcast_gradient_args_eager_fallback
#   broadcast_static_shape
#   broadcast_to
#   broadcast_to_eager_fallback
#   bucketize
#   bucketize_eager_fallback
#   build_ta_with_new_flow
#   builtins
#   case
#   cast
#   cast_eager_fallback
#   categorical
#   ceil
#   ceil_eager_fallback
#   check_numerics
#   check_numerics_eager_fallback
#   check_numerics_v2
#   check_numerics_v2_eager_fallback
#   check_ops
#   cholesky
#   cholesky_eager_fallback
#   cholesky_grad
#   cholesky_grad_eager_fallback
#   cholesky_solve
#   client
#   clip_by_average_norm
#   clip_by_global_norm
#   clip_by_norm
#   clip_by_value
#   clip_ops
#   collections
#   collections_abc
#   colocate_with
#   common_shapes
#   compare_and_bitpack
#   compare_and_bitpack_eager_fallback
#   compiler
#   complex
#   complex128
#   complex128_ref
#   complex64
#   complex64_ref
#   complex_abs
#   complex_abs_eager_fallback
#   composite_tensor
#   concat
#   concat_eager_fallback
#   concat_offset
#   concat_offset_eager_fallback
#   concat_v2
#   concat_v2_eager_fallback
#   cond
#   conditional_accumulator
#   conditional_accumulator_eager_fallback
#   confusion_matrix
#   conj
#   conj_eager_fallback
#   conjugate_transpose
#   conjugate_transpose_eager_fallback
#   const
#   const_eager_fallback
#   constant
#   constant_initializer
#   constant_op
#   container
#   context
#   contextlib
#   control_dependencies
#   control_flow_ops
#   control_flow_util
#   convert_to_int_tensor
#   convert_to_tensor
#   convert_to_tensor_or_indexed_slices
#   convert_to_tensor_or_sparse_tensor
#   convolutional_delta_orthogonal
#   convolutional_orthogonal_1d
#   convolutional_orthogonal_2d
#   convolutional_orthogonal_3d
#   cos
#   cos_eager_fallback
#   cosh
#   cosh_eager_fallback
#   count_nonzero
#   count_nonzero_v2
#   count_up_to
#   create_partitioned_variables
#   cross
#   cross_eager_fallback
#   cudnn_rnn_grad
#   cumprod
#   cumprod_eager_fallback
#   cumsum
#   cumsum_eager_fallback
#   cumulative_logsumexp
#   cumulative_logsumexp_eager_fallback
#   custom_gradient
#   data_flow_grad
#   dawsn
#   debug
#   debug_gradient_identity
#   debug_gradient_identity_eager_fallback
#   debug_gradient_ref_identity
#   debug_gradient_ref_identity_eager_fallback
#   decode_base64
#   decode_base64_eager_fallback
#   decode_compressed
#   decode_compressed_eager_fallback
#   decode_csv
#   decode_csv_eager_fallback
#   decode_csv_v2
#   decode_json_example
#   decode_json_example_eager_fallback
#   decode_padded_raw
#   decode_padded_raw_eager_fallback
#   decode_proto
#   decode_raw
#   decode_raw_eager_fallback
#   decode_raw_v1
#   deep_copy
#   deep_copy_eager_fallback
#   default_variable_creator
#   default_variable_creator_v2
#   delete_session_tensor
#   delete_session_tensor_eager_fallback
#   deprecated
#   deprecated_arg_values
#   deprecated_args
#   deprecated_endpoints
#   deprecation
#   depth_to_space
#   depth_to_space_eager_fallback
#   depth_to_space_v2
#   dequantize
#   dequantize_eager_fallback
#   deserialize_many_sparse
#   deserialize_many_sparse_eager_fallback
#   deserialize_sparse
#   deserialize_sparse_eager_fallback
#   device
#   diag
#   diag_eager_fallback
#   diag_part
#   diag_part_eager_fallback
#   digamma
#   digamma_eager_fallback
#   dispatch
#   div
#   div_eager_fallback
#   div_no_nan
#   div_no_nan_eager_fallback
#   divide
#   division
#   dlpack
#   double
#   double_ref
#   dtype_range
#   dtypes
#   dynamic_partition
#   dynamic_partition_eager_fallback
#   dynamic_stitch
#   dynamic_stitch_eager_fallback
#   eager
#   edit_distance
#   edit_distance_eager_fallback
#   eig
#   eig_eager_fallback
#   eigvals
#   einsum
#   einsum_eager_fallback
#   empty
#   empty_eager_fallback
#   encode_base64
#   encode_base64_eager_fallback
#   encode_proto
#   encode_resource_handle
#   ensure_shape
#   ensure_shape_eager_fallback
#   enum
#   enum_type_wrapper
#   equal
#   equal_eager_fallback
#   erf
#   erf_eager_fallback
#   erfc
#   erfc_eager_fallback
#   erfinv
#   erfinv_eager_fallback
#   errno
#   errors_impl
#   euclidean_norm
#   euclidean_norm_eager_fallback
#   exp
#   exp_eager_fallback
#   expand_dims
#   expand_dims_eager_fallback
#   expand_dims_v2
#   expint
#   expm1
#   expm1_eager_fallback
#   extract_image_patches
#   extract_image_patches_eager_fallback
#   extract_image_patches_v2
#   extract_volume_patches
#   extract_volume_patches_eager_fallback
#   eye
#   fake_quant_with_min_max_args
#   fake_quant_with_min_max_args_eager_fallback
#   fake_quant_with_min_max_args_gradient
#   fake_quant_with_min_max_args_gradient_eager_fallback
#   fake_quant_with_min_max_vars
#   fake_quant_with_min_max_vars_eager_fallback
#   fake_quant_with_min_max_vars_gradient
#   fake_quant_with_min_max_vars_gradient_eager_fallback
#   fake_quant_with_min_max_vars_per_channel
#   fake_quant_with_min_max_vars_per_channel_eager_fallback
#   fake_quant_with_min_max_vars_per_channel_gradient
#   fake_quant_with_min_max_vars_per_channel_gradient_eager_fallback
#   fake_queue
#   fake_queue_eager_fallback
#   fifo_queue
#   fifo_queue_eager_fallback
#   fifo_queue_v2
#   fifo_queue_v2_eager_fallback
#   file_io
#   fill
#   fill_eager_fallback
#   fingerprint
#   fingerprint_eager_fallback
#   fixed_length_record_reader
#   fixed_length_record_reader_eager_fallback
#   fixed_length_record_reader_v2
#   fixed_length_record_reader_v2_eager_fallback
#   fixed_size_partitioner
#   float16
#   float16_ref
#   float32
#   float32_ref
#   float64
#   float64_ref
#   floor
#   floor_div
#   floor_div_eager_fallback
#   floor_eager_fallback
#   floor_mod
#   floor_mod_eager_fallback
#   floordiv
#   floormod
#   foldl
#   foldl_v2
#   foldr
#   foldr_v2
#   framework
#   framework_ops
#   fresnel_cos
#   fresnel_sin
#   from_dense
#   function_utils
#   functools
#   gather
#   gather_eager_fallback
#   gather_nd
#   gather_nd_eager_fallback
#   gather_nd_v2
#   gather_v2
#   gather_v2_eager_fallback
#   gen_array_ops
#   gen_batch_ops
#   gen_control_flow_ops
#   gen_data_flow_ops
#   gen_functional_ops
#   gen_io_ops
#   gen_linalg_ops
#   gen_math_ops
#   gen_nn_ops
#   gen_parsing_ops
#   gen_random_ops
#   gen_sparse_ops
#   gen_special_math_ops
#   gen_state_ops
#   gen_stateless_random_ops
#   gen_string_ops
#   gen_xla_ops
#   get_canonical_name_for_symbol
#   get_collection
#   get_collection_ref
#   get_default_graph
#   get_default_session
#   get_local_variable
#   get_positive_axis
#   get_seed
#   get_session_handle
#   get_session_handle_eager_fallback
#   get_session_handle_v2
#   get_session_handle_v2_eager_fallback
#   get_session_tensor
#   get_session_tensor_eager_fallback
#   get_summary_op
#   get_variable
#   get_variable_scope
#   global_norm
#   global_variables
#   global_variables_initializer
#   glorot_normal_initializer
#   glorot_uniform_initializer
#   gradients
#   grappler
#   greater
#   greater_eager_fallback
#   greater_equal
#   greater_equal_eager_fallback
#   group
#   guarantee_const
#   guarantee_const_eager_fallback
#   half
#   half_ref
#   hashlib
#   he_normal
#   he_uniform
#   hessians
#   histogram_fixed_width
#   histogram_fixed_width_bins
#   identity
#   identity_eager_fallback
#   identity_initializer
#   identity_n
#   identity_n_eager_fallback
#   identity_reader
#   identity_reader_eager_fallback
#   identity_reader_v2
#   identity_reader_v2_eager_fallback
#   igamma
#   igamma_eager_fallback
#   igamma_grad_a
#   igamma_grad_a_eager_fallback
#   igammac
#   igammac_eager_fallback
#   imag
#   imag_eager_fallback
#   immutable_const
#   immutable_const_eager_fallback
#   imp
#   import_graph_def
#   initialize_all_tables
#   initialize_all_variables
#   initialize_local_variables
#   initialize_variables
#   inplace_add
#   inplace_add_eager_fallback
#   inplace_sub
#   inplace_sub_eager_fallback
#   inplace_update
#   inplace_update_eager_fallback
#   int16
#   int16_ref
#   int32
#   int32_ref
#   int64
#   int64_ref
#   int8
#   int8_ref
#   inv
#   inv_eager_fallback
#   inv_grad
#   inv_grad_eager_fallback
#   invert_permutation
#   invert_permutation_eager_fallback
#   is_finite
#   is_finite_eager_fallback
#   is_inf
#   is_inf_eager_fallback
#   is_nan
#   is_nan_eager_fallback
#   is_non_decreasing
#   is_numeric_tensor
#   is_strictly_increasing
#   is_variable_initialized
#   itertools
#   lbeta
#   lecun_normal
#   lecun_uniform
#   less
#   less_eager_fallback
#   less_equal
#   less_equal_eager_fallback
#   lgamma
#   lgamma_eager_fallback
#   lib
#   lin_space
#   lin_space_eager_fallback
#   linalg_ops_impl
#   linspace
#   list_diff
#   list_diff_eager_fallback
#   list_ops
#   listdiff
#   lmdb_reader
#   lmdb_reader_eager_fallback
#   load_file_system_library
#   load_library
#   load_op_library
#   local_variables
#   local_variables_initializer
#   log
#   log1p
#   log1p_eager_fallback
#   log_eager_fallback
#   log_matrix_determinant
#   log_matrix_determinant_eager_fallback
#   log_sigmoid
#   logical_and
#   logical_and_eager_fallback
#   logical_not
#   logical_not_eager_fallback
#   logical_or
#   logical_or_eager_fallback
#   logical_xor
#   loss_scaling_gradient_tape
#   lower_bound
#   lower_bound_eager_fallback
#   lu
#   lu_eager_fallback
#   make_ndarray
#   make_template
#   make_tensor_proto
#   manip_grad
#   map_clear
#   map_clear_eager_fallback
#   map_fn
#   map_incomplete_size
#   map_incomplete_size_eager_fallback
#   map_peek
#   map_peek_eager_fallback
#   map_size
#   map_size_eager_fallback
#   map_stage
#   map_stage_eager_fallback
#   map_unstage
#   map_unstage_eager_fallback
#   map_unstage_no_key
#   map_unstage_no_key_eager_fallback
#   mat_mul
#   mat_mul_eager_fallback
#   matching_files
#   matching_files_eager_fallback
#   math
#   math_grad
#   math_ops
#   matmul
#   matrix_band_part
#   matrix_band_part_eager_fallback
#   matrix_determinant
#   matrix_determinant_eager_fallback
#   matrix_diag
#   matrix_diag_eager_fallback
#   matrix_diag_part
#   matrix_diag_part_eager_fallback
#   matrix_diag_part_v2
#   matrix_diag_part_v2_eager_fallback
#   matrix_diag_part_v3
#   matrix_diag_part_v3_eager_fallback
#   matrix_diag_v2
#   matrix_diag_v2_eager_fallback
#   matrix_diag_v3
#   matrix_diag_v3_eager_fallback
#   matrix_exponential
#   matrix_exponential_eager_fallback
#   matrix_inverse
#   matrix_inverse_eager_fallback
#   matrix_logarithm
#   matrix_logarithm_eager_fallback
#   matrix_set_diag
#   matrix_set_diag_eager_fallback
#   matrix_set_diag_v2
#   matrix_set_diag_v2_eager_fallback
#   matrix_set_diag_v3
#   matrix_set_diag_v3_eager_fallback
#   matrix_solve
#   matrix_solve_eager_fallback
#   matrix_solve_ls
#   matrix_solve_ls_eager_fallback
#   matrix_square_root
#   matrix_square_root_eager_fallback
#   matrix_transpose
#   matrix_triangular_solve
#   matrix_triangular_solve_eager_fallback
#   matvec
#   maximum
#   maximum_eager_fallback
#   mean
#   mean_eager_fallback
#   merge_v2_checkpoints
#   merge_v2_checkpoints_eager_fallback
#   meshgrid
#   min_max_variable_partitioner
#   minimum
#   minimum_eager_fallback
#   mirror_pad
#   mirror_pad_eager_fallback
#   mirror_pad_grad
#   mirror_pad_grad_eager_fallback
#   mod
#   mod_eager_fallback
#   model_variables
#   moving_average_variables
#   mul
#   mul_eager_fallback
#   mul_no_nan
#   mul_no_nan_eager_fallback
#   multinomial
#   multinomial_categorical_impl
#   multinomial_eager_fallback
#   multiply
#   multiply_no_nan
#   name_scope
#   ndtri
#   ndtri_eager_fallback
#   neg
#   neg_eager_fallback
#   negative
#   nest
#   newaxis
#   next_after
#   next_after_eager_fallback
#   nextafter
#   nn_ops
#   no_op
#   no_regularizer
#   norm
#   norm_v2
#   not_equal
#   not_equal_eager_fallback
#   np_resource
#   numbers
#   object_identity
#   one_hot
#   one_hot_eager_fallback
#   ones
#   ones_initializer
#   ones_like
#   ones_like_eager_fallback
#   ones_like_impl
#   ones_like_v2
#   op_scope
#   ops
#   opt_einsum
#   ordered_map_clear
#   ordered_map_clear_eager_fallback
#   ordered_map_incomplete_size
#   ordered_map_incomplete_size_eager_fallback
#   ordered_map_peek
#   ordered_map_peek_eager_fallback
#   ordered_map_size
#   ordered_map_size_eager_fallback
#   ordered_map_stage
#   ordered_map_stage_eager_fallback
#   ordered_map_unstage
#   ordered_map_unstage_eager_fallback
#   ordered_map_unstage_no_key
#   ordered_map_unstage_no_key_eager_fallback
#   orthogonal_initializer
#   os
#   pack
#   pack_eager_fallback
#   pad
#   pad_eager_fallback
#   pad_v2
#   pad_v2_eager_fallback
#   padding_fifo_queue
#   padding_fifo_queue_eager_fallback
#   padding_fifo_queue_v2
#   padding_fifo_queue_v2_eager_fallback
#   parallel_concat
#   parallel_concat_eager_fallback
#   parallel_dynamic_stitch
#   parallel_dynamic_stitch_eager_fallback
#   parallel_stack
#   parameterized_truncated_normal
#   parameterized_truncated_normal_eager_fallback
#   parse_example
#   parse_example_eager_fallback
#   parse_example_v2
#   parse_example_v2_eager_fallback
#   parse_sequence_example
#   parse_sequence_example_eager_fallback
#   parse_sequence_example_v2
#   parse_sequence_example_v2_eager_fallback
#   parse_single_example
#   parse_single_example_eager_fallback
#   parse_single_example_v2
#   parse_single_sequence_example
#   parse_single_sequence_example_eager_fallback
#   parse_tensor
#   parse_tensor_eager_fallback
#   parsing_config
#   partitioned_call
#   pdt
#   placeholder
#   placeholder_eager_fallback
#   placeholder_v2
#   placeholder_v2_eager_fallback
#   placeholder_with_default
#   placeholder_with_default_eager_fallback
#   platform
#   polygamma
#   polygamma_eager_fallback
#   polyval
#   pow
#   prevent_gradient
#   prevent_gradient_eager_fallback
#   print_function
#   priority_queue
#   priority_queue_eager_fallback
#   priority_queue_v2
#   priority_queue_v2_eager_fallback
#   prod
#   prod_eager_fallback
#   py_func
#   py_tf
#   pydev
#   pywrap_mlir
#   pywrap_tensorflow_internal
#   pywrap_tf_session
#   pywrap_tfe
#   qint16
#   qint16_ref
#   qint32
#   qint32_ref
#   qint8
#   qint8_ref
#   qr
#   qr_eager_fallback
#   quantize
#   quantize_and_dequantize
#   quantize_and_dequantize_eager_fallback
#   quantize_and_dequantize_v2
#   quantize_and_dequantize_v2_eager_fallback
#   quantize_and_dequantize_v3
#   quantize_and_dequantize_v3_eager_fallback
#   quantize_down_and_shrink_range
#   quantize_down_and_shrink_range_eager_fallback
#   quantize_v2
#   quantize_v2_eager_fallback
#   quantized_add
#   quantized_add_eager_fallback
#   quantized_concat
#   quantized_concat_eager_fallback
#   quantized_instance_norm
#   quantized_instance_norm_eager_fallback
#   quantized_mat_mul
#   quantized_mat_mul_eager_fallback
#   quantized_mul
#   quantized_mul_eager_fallback
#   quantized_reshape
#   quantized_reshape_eager_fallback
#   queue_close
#   queue_close_eager_fallback
#   queue_close_v2
#   queue_close_v2_eager_fallback
#   queue_dequeue
#   queue_dequeue_eager_fallback
#   queue_dequeue_many
#   queue_dequeue_many_eager_fallback
#   queue_dequeue_many_v2
#   queue_dequeue_many_v2_eager_fallback
#   queue_dequeue_up_to
#   queue_dequeue_up_to_eager_fallback
#   queue_dequeue_up_to_v2
#   queue_dequeue_up_to_v2_eager_fallback
#   queue_dequeue_v2
#   queue_dequeue_v2_eager_fallback
#   queue_enqueue
#   queue_enqueue_eager_fallback
#   queue_enqueue_many
#   queue_enqueue_many_eager_fallback
#   queue_enqueue_many_v2
#   queue_enqueue_many_v2_eager_fallback
#   queue_enqueue_v2
#   queue_enqueue_v2_eager_fallback
#   queue_is_closed
#   queue_is_closed_eager_fallback
#   queue_is_closed_v2
#   queue_is_closed_v2_eager_fallback
#   queue_size
#   queue_size_eager_fallback
#   queue_size_v2
#   queue_size_v2_eager_fallback
#   quint16
#   quint16_ref
#   quint8
#   quint8_ref
#   random_crop
#   random_gamma
#   random_gamma_eager_fallback
#   random_gamma_grad
#   random_gamma_grad_eager_fallback
#   random_grad
#   random_normal
#   random_normal_initializer
#   random_ops
#   random_poisson
#   random_poisson_eager_fallback
#   random_poisson_v2
#   random_poisson_v2_eager_fallback
#   random_seed
#   random_shuffle
#   random_shuffle_eager_fallback
#   random_shuffle_queue
#   random_shuffle_queue_eager_fallback
#   random_shuffle_queue_v2
#   random_shuffle_queue_v2_eager_fallback
#   random_standard_normal
#   random_standard_normal_eager_fallback
#   random_uniform
#   random_uniform_eager_fallback
#   random_uniform_initializer
#   random_uniform_int
#   random_uniform_int_eager_fallback
#   range
#   rank
#   rank_eager_fallback
#   rank_internal
#   re
#   read_file
#   read_file_eager_fallback
#   reader_num_records_produced
#   reader_num_records_produced_eager_fallback
#   reader_num_records_produced_v2
#   reader_num_records_produced_v2_eager_fallback
#   reader_num_work_units_completed
#   reader_num_work_units_completed_eager_fallback
#   reader_num_work_units_completed_v2
#   reader_num_work_units_completed_v2_eager_fallback
#   reader_read
#   reader_read_eager_fallback
#   reader_read_up_to
#   reader_read_up_to_eager_fallback
#   reader_read_up_to_v2
#   reader_read_up_to_v2_eager_fallback
#   reader_read_v2
#   reader_read_v2_eager_fallback
#   reader_reset
#   reader_reset_eager_fallback
#   reader_reset_v2
#   reader_reset_v2_eager_fallback
#   reader_restore_state
#   reader_restore_state_eager_fallback
#   reader_restore_state_v2
#   reader_restore_state_v2_eager_fallback
#   reader_serialize_state
#   reader_serialize_state_eager_fallback
#   reader_serialize_state_v2
#   reader_serialize_state_v2_eager_fallback
#   real
#   real_div
#   real_div_eager_fallback
#   real_eager_fallback
#   realdiv
#   reciprocal
#   reciprocal_eager_fallback
#   reciprocal_grad
#   reciprocal_grad_eager_fallback
#   reciprocal_no_nan
#   record_input
#   record_input_eager_fallback
#   reduce_all
#   reduce_all_v1
#   reduce_any
#   reduce_any_v1
#   reduce_euclidean_norm
#   reduce_join
#   reduce_join_eager_fallback
#   reduce_join_v2
#   reduce_logsumexp
#   reduce_logsumexp_v1
#   reduce_max
#   reduce_max_v1
#   reduce_max_with_dims
#   reduce_mean
#   reduce_mean_v1
#   reduce_min
#   reduce_min_v1
#   reduce_prod
#   reduce_prod_v1
#   reduce_std
#   reduce_sum
#   reduce_sum_v1
#   reduce_sum_with_dims
#   reduce_variance
#   reduced_shape
#   ref_identity
#   ref_identity_eager_fallback
#   regex_full_match
#   regex_full_match_eager_fallback
#   regex_replace
#   regex_replace_eager_fallback
#   register_tensor_conversion_function
#   remote_call
#   repeat
#   repeat_with_axis
#   report_uninitialized_variables
#   requantization_range
#   requantization_range_eager_fallback
#   requantization_range_per_channel
#   requantization_range_per_channel_eager_fallback
#   requantize
#   requantize_eager_fallback
#   requantize_per_channel
#   requantize_per_channel_eager_fallback
#   required_space_to_batch_paddings
#   reset_default_graph
#   reshape
#   reshape_eager_fallback
#   resource
#   resource_accumulator_apply_gradient
#   resource_accumulator_apply_gradient_eager_fallback
#   resource_accumulator_num_accumulated
#   resource_accumulator_num_accumulated_eager_fallback
#   resource_accumulator_set_global_step
#   resource_accumulator_set_global_step_eager_fallback
#   resource_accumulator_take_gradient
#   resource_accumulator_take_gradient_eager_fallback
#   resource_conditional_accumulator
#   resource_conditional_accumulator_eager_fallback
#   resource_handle_pb2
#   resource_ref
#   resource_strided_slice_assign
#   resource_strided_slice_assign_eager_fallback
#   resource_variable_ops
#   restore
#   restore_eager_fallback
#   restore_slice
#   restore_slice_eager_fallback
#   restore_v2
#   restore_v2_eager_fallback
#   reverse
#   reverse_eager_fallback
#   reverse_sequence
#   reverse_sequence_eager_fallback
#   reverse_sequence_v2
#   reverse_v2
#   reverse_v2_eager_fallback
#   rint
#   rint_eager_fallback
#   rnn_grad
#   roll
#   round
#   round_eager_fallback
#   rsqrt
#   rsqrt_eager_fallback
#   rsqrt_grad
#   rsqrt_grad_eager_fallback
#   saturate_cast
#   save
#   save_eager_fallback
#   save_slices
#   save_slices_eager_fallback
#   save_v2
#   save_v2_eager_fallback
#   scalar_mul
#   scalar_mul_v2
#   scan
#   scan_v2
#   scatter_add
#   scatter_div
#   scatter_max
#   scatter_min
#   scatter_mul
#   scatter_nd
#   scatter_nd_add
#   scatter_nd_eager_fallback
#   scatter_nd_non_aliasing_add
#   scatter_nd_non_aliasing_add_eager_fallback
#   scatter_nd_sub
#   scatter_nd_update
#   scatter_sub
#   scatter_update
#   searchsorted
#   segment_max
#   segment_max_eager_fallback
#   segment_mean
#   segment_mean_eager_fallback
#   segment_min
#   segment_min_eager_fallback
#   segment_prod
#   segment_prod_eager_fallback
#   segment_sum
#   segment_sum_eager_fallback
#   select
#   select_eager_fallback
#   select_v2
#   select_v2_eager_fallback
#   self_adjoint_eig
#   self_adjoint_eig_eager_fallback
#   self_adjoint_eig_v2
#   self_adjoint_eig_v2_eager_fallback
#   self_adjoint_eigvals
#   sequence_mask
#   serialize_many_sparse
#   serialize_many_sparse_eager_fallback
#   serialize_many_sparse_v2
#   serialize_sparse
#   serialize_sparse_eager_fallback
#   serialize_sparse_v2
#   serialize_tensor
#   serialize_tensor_eager_fallback
#   set_random_seed
#   setdiff1d
#   shape
#   shape_eager_fallback
#   shape_internal
#   shape_n
#   shape_n_eager_fallback
#   shape_v2
#   sharded_filename
#   sharded_filename_eager_fallback
#   sharded_filespec
#   sharded_filespec_eager_fallback
#   sigmoid
#   sigmoid_eager_fallback
#   sigmoid_grad
#   sigmoid_grad_eager_fallback
#   sign
#   sign_eager_fallback
#   sin
#   sin_eager_fallback
#   sinh
#   sinh_eager_fallback
#   six
#   size
#   size_eager_fallback
#   size_internal
#   size_v2
#   slice
#   snapshot
#   snapshot_eager_fallback
#   sobol_sample
#   sobol_sample_eager_fallback
#   sort
#   space_to_batch
#   space_to_batch_eager_fallback
#   space_to_batch_nd
#   space_to_batch_nd_eager_fallback
#   space_to_batch_v2
#   space_to_depth
#   space_to_depth_eager_fallback
#   space_to_depth_v2
#   sparse_accumulator_apply_gradient
#   sparse_accumulator_apply_gradient_eager_fallback
#   sparse_accumulator_take_gradient
#   sparse_accumulator_take_gradient_eager_fallback
#   sparse_add
#   sparse_add_eager_fallback
#   sparse_add_grad
#   sparse_add_grad_eager_fallback
#   sparse_add_v2
#   sparse_concat
#   sparse_concat_eager_fallback
#   sparse_concat_v2
#   sparse_conditional_accumulator
#   sparse_conditional_accumulator_eager_fallback
#   sparse_cross
#   sparse_cross_eager_fallback
#   sparse_cross_hashed
#   sparse_dense_cwise_add
#   sparse_dense_cwise_add_eager_fallback
#   sparse_dense_cwise_div
#   sparse_dense_cwise_div_eager_fallback
#   sparse_dense_cwise_mul
#   sparse_dense_cwise_mul_eager_fallback
#   sparse_expand_dims
#   sparse_eye
#   sparse_fill_empty_rows
#   sparse_fill_empty_rows_eager_fallback
#   sparse_fill_empty_rows_grad
#   sparse_fill_empty_rows_grad_eager_fallback
#   sparse_grad
#   sparse_mask
#   sparse_mat_mul
#   sparse_mat_mul_eager_fallback
#   sparse_matmul
#   sparse_maximum
#   sparse_merge
#   sparse_merge_impl
#   sparse_minimum
#   sparse_placeholder
#   sparse_reduce_max
#   sparse_reduce_max_eager_fallback
#   sparse_reduce_max_sparse
#   sparse_reduce_max_sparse_eager_fallback
#   sparse_reduce_max_v2
#   sparse_reduce_sum
#   sparse_reduce_sum_eager_fallback
#   sparse_reduce_sum_sparse
#   sparse_reduce_sum_sparse_eager_fallback
#   sparse_reduce_sum_v2
#   sparse_reorder
#   sparse_reorder_eager_fallback
#   sparse_reset_shape
#   sparse_reshape
#   sparse_reshape_eager_fallback
#   sparse_retain
#   sparse_segment_mean
#   sparse_segment_mean_eager_fallback
#   sparse_segment_mean_grad
#   sparse_segment_mean_grad_eager_fallback
#   sparse_segment_mean_v2
#   sparse_segment_mean_with_num_segments
#   sparse_segment_mean_with_num_segments_eager_fallback
#   sparse_segment_sqrt_n
#   sparse_segment_sqrt_n_eager_fallback
#   sparse_segment_sqrt_n_grad
#   sparse_segment_sqrt_n_grad_eager_fallback
#   sparse_segment_sqrt_n_v2
#   sparse_segment_sqrt_n_with_num_segments
#   sparse_segment_sqrt_n_with_num_segments_eager_fallback
#   sparse_segment_sum
#   sparse_segment_sum_eager_fallback
#   sparse_segment_sum_v2
#   sparse_segment_sum_with_num_segments
#   sparse_segment_sum_with_num_segments_eager_fallback
#   sparse_slice
#   sparse_slice_eager_fallback
#   sparse_slice_grad
#   sparse_slice_grad_eager_fallback
#   sparse_softmax
#   sparse_softmax_eager_fallback
#   sparse_sparse_maximum
#   sparse_sparse_maximum_eager_fallback
#   sparse_sparse_minimum
#   sparse_sparse_minimum_eager_fallback
#   sparse_split
#   sparse_split_eager_fallback
#   sparse_split_v2
#   sparse_tensor
#   sparse_tensor_dense_add
#   sparse_tensor_dense_add_eager_fallback
#   sparse_tensor_dense_mat_mul
#   sparse_tensor_dense_mat_mul_eager_fallback
#   sparse_tensor_dense_matmul
#   sparse_tensor_to_dense
#   sparse_to_dense
#   sparse_to_dense_eager_fallback
#   sparse_to_indicator
#   sparse_transpose
#   spence
#   split
#   split_eager_fallback
#   split_v
#   split_v_eager_fallback
#   sqrt
#   sqrt_eager_fallback
#   sqrt_grad
#   sqrt_grad_eager_fallback
#   square
#   square_eager_fallback
#   squared_difference
#   squared_difference_eager_fallback
#   squeeze
#   squeeze_eager_fallback
#   squeeze_v2
#   stack
#   stack_close
#   stack_close_eager_fallback
#   stack_close_v2
#   stack_close_v2_eager_fallback
#   stack_pop
#   stack_pop_eager_fallback
#   stack_pop_v2
#   stack_pop_v2_eager_fallback
#   stack_push
#   stack_push_eager_fallback
#   stack_push_v2
#   stack_push_v2_eager_fallback
#   stack_v2
#   stack_v2_eager_fallback
#   stage
#   stage_clear
#   stage_clear_eager_fallback
#   stage_eager_fallback
#   stage_peek
#   stage_peek_eager_fallback
#   stage_size
#   stage_size_eager_fallback
#   state_grad
#   state_ops
#   stateless_categorical
#   stateless_multinomial
#   stateless_multinomial_categorical_impl
#   stateless_random_binomial
#   stateless_random_gamma
#   stateless_random_normal
#   stateless_random_poisson
#   stateless_random_uniform
#   stateless_truncated_normal
#   static_regex_full_match
#   static_regex_full_match_eager_fallback
#   static_regex_replace
#   static_regex_replace_eager_fallback
#   stop_gradient
#   stop_gradient_eager_fallback
#   strided_slice
#   strided_slice_assign
#   strided_slice_assign_eager_fallback
#   strided_slice_eager_fallback
#   strided_slice_grad
#   strided_slice_grad_eager_fallback
#   string
#   string_format
#   string_format_eager_fallback
#   string_join
#   string_join_eager_fallback
#   string_length
#   string_length_eager_fallback
#   string_length_v2
#   string_lower
#   string_lower_eager_fallback
#   string_n_grams
#   string_n_grams_eager_fallback
#   string_ref
#   string_split
#   string_split_eager_fallback
#   string_split_v2
#   string_split_v2_eager_fallback
#   string_strip
#   string_strip_eager_fallback
#   string_to_hash_bucket
#   string_to_hash_bucket_eager_fallback
#   string_to_hash_bucket_fast
#   string_to_hash_bucket_fast_eager_fallback
#   string_to_hash_bucket_strong
#   string_to_hash_bucket_strong_eager_fallback
#   string_to_hash_bucket_v1
#   string_to_number
#   string_to_number_eager_fallback
#   string_to_number_v1
#   string_upper
#   string_upper_eager_fallback
#   sub
#   sub_eager_fallback
#   substr
#   substr_deprecated
#   substr_eager_fallback
#   substr_v2
#   subtract
#   svd
#   svd_eager_fallback
#   symbolic_gradient
#   tables_initializer
#   take_many_sparse_from_tensors_map
#   take_many_sparse_from_tensors_map_eager_fallback
#   tan
#   tan_eager_fallback
#   tanh
#   tanh_eager_fallback
#   tanh_grad
#   tanh_grad_eager_fallback
#   tensor_array
#   tensor_array_close
#   tensor_array_close_eager_fallback
#   tensor_array_close_v2
#   tensor_array_close_v2_eager_fallback
#   tensor_array_close_v3
#   tensor_array_close_v3_eager_fallback
#   tensor_array_concat
#   tensor_array_concat_eager_fallback
#   tensor_array_concat_v2
#   tensor_array_concat_v2_eager_fallback
#   tensor_array_concat_v3
#   tensor_array_concat_v3_eager_fallback
#   tensor_array_eager_fallback
#   tensor_array_gather
#   tensor_array_gather_eager_fallback
#   tensor_array_gather_v2
#   tensor_array_gather_v2_eager_fallback
#   tensor_array_gather_v3
#   tensor_array_gather_v3_eager_fallback
#   tensor_array_grad
#   tensor_array_grad_eager_fallback
#   tensor_array_grad_v2
#   tensor_array_grad_v2_eager_fallback
#   tensor_array_grad_v3
#   tensor_array_grad_v3_eager_fallback
#   tensor_array_grad_with_shape
#   tensor_array_grad_with_shape_eager_fallback
#   tensor_array_ops
#   tensor_array_pack
#   tensor_array_pack_eager_fallback
#   tensor_array_read
#   tensor_array_read_eager_fallback
#   tensor_array_read_v2
#   tensor_array_read_v2_eager_fallback
#   tensor_array_read_v3
#   tensor_array_read_v3_eager_fallback
#   tensor_array_scatter
#   tensor_array_scatter_eager_fallback
#   tensor_array_scatter_v2
#   tensor_array_scatter_v2_eager_fallback
#   tensor_array_scatter_v3
#   tensor_array_scatter_v3_eager_fallback
#   tensor_array_size
#   tensor_array_size_eager_fallback
#   tensor_array_size_v2
#   tensor_array_size_v2_eager_fallback
#   tensor_array_size_v3
#   tensor_array_size_v3_eager_fallback
#   tensor_array_split
#   tensor_array_split_eager_fallback
#   tensor_array_split_v2
#   tensor_array_split_v2_eager_fallback
#   tensor_array_split_v3
#   tensor_array_split_v3_eager_fallback
#   tensor_array_unpack
#   tensor_array_unpack_eager_fallback
#   tensor_array_v2
#   tensor_array_v2_eager_fallback
#   tensor_array_v3
#   tensor_array_v3_eager_fallback
#   tensor_array_write
#   tensor_array_write_eager_fallback
#   tensor_array_write_v2
#   tensor_array_write_v2_eager_fallback
#   tensor_array_write_v3
#   tensor_array_write_v3_eager_fallback
#   tensor_equals
#   tensor_not_equals
#   tensor_scatter_add
#   tensor_scatter_add_eager_fallback
#   tensor_scatter_sub
#   tensor_scatter_sub_eager_fallback
#   tensor_scatter_update
#   tensor_scatter_update_eager_fallback
#   tensor_shape
#   tensor_spec
#   tensor_strided_slice_update
#   tensor_strided_slice_update_eager_fallback
#   tensor_util
#   tensordot
#   tensorflow_dot_core_dot_framework_dot_attr__value__pb2
#   tensorflow_dot_core_dot_framework_dot_cost__graph__pb2
#   tensorflow_dot_core_dot_framework_dot_function__pb2
#   tensorflow_dot_core_dot_framework_dot_graph__pb2
#   tensorflow_dot_core_dot_framework_dot_node__def__pb2
#   tensorflow_dot_core_dot_framework_dot_step__stats__pb2
#   tensorflow_dot_core_dot_framework_dot_summary__pb2
#   tensorflow_dot_core_dot_framework_dot_tensor__pb2
#   tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
#   tensorflow_dot_core_dot_framework_dot_types__pb2
#   tensorflow_dot_core_dot_framework_dot_versions__pb2
#   tensorflow_dot_core_dot_protobuf_dot_cluster__pb2
#   tensorflow_dot_core_dot_protobuf_dot_config__pb2
#   tensorflow_dot_core_dot_protobuf_dot_debug__pb2
#   tensorflow_dot_core_dot_protobuf_dot_device__filters__pb2
#   tensorflow_dot_core_dot_protobuf_dot_rewriter__config__pb2
#   text_line_reader
#   text_line_reader_eager_fallback
#   text_line_reader_v2
#   text_line_reader_v2_eager_fallback
#   tf2
#   tf_decorator
#   tf_inspect
#   tf_record_reader
#   tf_record_reader_eager_fallback
#   tf_record_reader_v2
#   tf_record_reader_v2_eager_fallback
#   tf_should_use
#   threading
#   tile
#   tile_eager_fallback
#   tile_grad
#   tile_grad_eager_fallback
#   tile_one_dimension
#   timestamp
#   to_bfloat16
#   to_complex128
#   to_complex64
#   to_double
#   to_float
#   to_int32
#   to_int64
#   tpu
#   trace
#   trackable
#   trainable_variables
#   training
#   transpose
#   transpose_eager_fallback
#   transpose_v2
#   tridiagonal_mat_mul
#   tridiagonal_mat_mul_eager_fallback
#   tridiagonal_solve
#   tridiagonal_solve_eager_fallback
#   trt
#   truediv
#   truncate_div
#   truncate_div_eager_fallback
#   truncate_mod
#   truncate_mod_eager_fallback
#   truncated_normal
#   truncated_normal_eager_fallback
#   truncated_normal_initializer
#   truncatediv
#   truncatemod
#   tuple
#   type_spec
#   types_pb2
#   uint16
#   uint16_ref
#   uint32
#   uint32_ref
#   uint64
#   uint64_ref
#   uint8
#   uint8_ref
#   unary_op
#   unbatch
#   unbatch_eager_fallback
#   unbatch_grad
#   unbatch_grad_eager_fallback
#   unicode_decode
#   unicode_decode_eager_fallback
#   unicode_decode_with_offsets
#   unicode_decode_with_offsets_eager_fallback
#   unicode_encode
#   unicode_encode_eager_fallback
#   unicode_script
#   unicode_script_eager_fallback
#   unicode_transcode
#   unicode_transcode_eager_fallback
#   uniform_unit_scaling_initializer
#   unique
#   unique_eager_fallback
#   unique_v2
#   unique_v2_eager_fallback
#   unique_with_counts
#   unique_with_counts_eager_fallback
#   unique_with_counts_v2
#   unique_with_counts_v2_eager_fallback
#   unpack
#   unpack_eager_fallback
#   unravel_index
#   unravel_index_eager_fallback
#   unsorted_segment_join
#   unsorted_segment_join_eager_fallback
#   unsorted_segment_max
#   unsorted_segment_max_eager_fallback
#   unsorted_segment_mean
#   unsorted_segment_min
#   unsorted_segment_min_eager_fallback
#   unsorted_segment_prod
#   unsorted_segment_prod_eager_fallback
#   unsorted_segment_sqrt_n
#   unsorted_segment_sum
#   unsorted_segment_sum_eager_fallback
#   unstack
#   unstage
#   unstage_eager_fallback
#   upper_bound
#   upper_bound_eager_fallback
#   util
#   util_compat
#   validate_synchronization_aggregation_trainable
#   variable_axis_size_partitioner
#   variable_op_scope
#   variable_pb2
#   variable_scope
#   variables_initializer
#   variance_scaling_initializer
#   variant
#   variant_ref
#   vectorized_map
#   verify_tensor_all_finite
#   verify_tensor_all_finite_v2
#   vs
#   weakref
#   where
#   where_eager_fallback
#   where_v2
#   while_loop
#   whole_file_reader
#   whole_file_reader_eager_fallback
#   whole_file_reader_v2
#   whole_file_reader_v2_eager_fallback
#   wrap_function
#   write_file
#   write_file_eager_fallback
#   xdivy
#   xdivy_eager_fallback
#   xlog1py
#   xlog1py_eager_fallback
#   xlogy
#   xlogy_eager_fallback
#   xrange
#   zeros
#   zeros_initializer
#   zeros_like
#   zeros_like_eager_fallback
#   zeros_like_impl
#   zeros_like_v2
#   zeta
#   zeta_eager_fallback
