def GpuSupportsHalfMatMulAndConv() -> bool: ...
def IsBuiltWithNvcc() -> bool: ...
def IsBuiltWithROCm() -> bool: ...
def IsBuiltWithXLA() -> bool: ...
def IsGoogleCudaEnabled() -> bool: ...
def IsMklEnabled() -> bool: ...
