def ExperimentalConvertSavedModelToMlir(arg0: str, arg1: str, arg2: bool) -> str: ...
def ExperimentalConvertSavedModelV1ToMlir(arg0: str, arg1: str, arg2: bool) -> str: ...
def ExperimentalRunPassPipeline(arg0: str, arg1: str, arg2: bool) -> str: ...
def ImportGraphDef(arg0: str, arg1: str) -> str: ...
