def Close(arg0: str) -> None: ...
def FlushExecutionFiles(arg0: str) -> None: ...
def FlushNonExecutionFiles(arg0: str) -> None: ...
def Init(arg0: str, arg1: int) -> None: ...
def RegisterDeviceAndGetId(arg0: str, arg1: str) -> int: ...
def WriteDebuggedGraph(arg0: str, arg1: object) -> None: ...
def WriteExecution(arg0: str, arg1: object) -> None: ...
def WriteGraphExecutionTrace(arg0: str, arg1: object) -> None: ...
def WriteGraphOpCreation(arg0: str, arg1: object) -> None: ...
def WriteSourceFile(arg0: str, arg1: object) -> None: ...
def WriteStackFrameWithId(arg0: str, arg1: object) -> None: ...
