from typing import Any, Dict, List, Tuple

class tensorflow::grappler::Cluster:
    def __init__(self, *args, **kwargs) -> None: ...

def TF_DeterminePeakMemoryUsage(arg0, arg1) -> Dict[str,Tuple[int,List[Tuple[str,int,int,int,int]]]]: ...
def TF_EstimatePerformance(arg0: bytes) -> float: ...
def TF_GetSupportedDevices(arg0, arg1) -> Dict[str,List[str]]: ...
def TF_ListAvailableOps() -> List[str]: ...
def TF_ListDevices(arg0) -> List[bytes]: ...
def TF_MeasureCosts(arg0, arg1, arg2: bool) -> Tuple[List[bytes],float,bytes]: ...
def TF_NewCluster(*args, **kwargs) -> Any: ...
def TF_NewVirtualCluster(*args, **kwargs) -> Any: ...
def TF_ShutdownCluster(arg0) -> None: ...
