class EventsWriter:
    def __init__(self, arg0: str) -> None: ...
    def Close(self) -> Status: ...
    def FileName(self) -> str: ...
    def Flush(self) -> Status: ...
    def InitWithSuffix(self, arg0: str) -> Status: ...
    def WriteEvent(self, arg0: object) -> None: ...
    def _WriteSerializedEvent(self, arg0: str) -> None: ...
