from typing import Any, ClassVar

class CheckpointReader:
    get_tensor: ClassVar[function] = ...
    get_variable_to_dtype_map: ClassVar[function] = ...
    has_tensor: ClassVar[function] = ...
    def __init__(self, arg0: str) -> None: ...
    def CheckpointReader_GetTensor(self, *args, **kwargs) -> Any: ...
    def _GetVariableToDataTypeMap(self, *args, **kwargs) -> Any: ...
    def _HasTensor(self, arg0: str) -> bool: ...
    def debug_string(self) -> bytes: ...
    def get_variable_to_shape_map(self, *args, **kwargs) -> Any: ...
