from typing import overload

class FrameSummary:
    def __init__(self, *args, **kwargs) -> None: ...
    def __eq__(self, arg0: FrameSummary) -> bool: ...
    def __getitem__(self, arg0: object) -> object: ...
    def __iter__(self) -> iterator: ...
    def __len__(self) -> int: ...
    def __ne__(self, arg0: FrameSummary) -> bool: ...
    @property
    def filename(self) -> str: ...
    @property
    def line(self) -> object: ...
    @property
    def lineno(self) -> int: ...
    @property
    def name(self) -> str: ...

class StackSummary:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: StackSummary) -> None: ...
    @overload
    def __init__(self, arg0: iterable) -> None: ...
    def append(self, x: FrameSummary) -> None: ...
    def count(self, x: FrameSummary) -> int: ...
    @overload
    def extend(self, L: StackSummary) -> None: ...
    @overload
    def extend(self, L: iterable) -> None: ...
    def insert(self, i: int, x: FrameSummary) -> None: ...
    @overload
    def pop(self) -> FrameSummary: ...
    @overload
    def pop(self, i: int) -> FrameSummary: ...
    def remove(self, x: FrameSummary) -> None: ...
    def __bool__(self) -> bool: ...
    def __contains__(self, x: FrameSummary) -> bool: ...
    @overload
    def __delitem__(self, arg0: int) -> None: ...
    @overload
    def __delitem__(self, arg0: slice) -> None: ...
    def __eq__(self, arg0: StackSummary) -> bool: ...
    @overload
    def __getitem__(self, s: slice) -> StackSummary: ...
    @overload
    def __getitem__(self, arg0: int) -> FrameSummary: ...
    @overload
    def __getitem__(self, arg0: int) -> FrameSummary: ...
    def __iter__(self) -> iterator: ...
    def __len__(self) -> int: ...
    def __ne__(self, arg0: StackSummary) -> bool: ...
    @overload
    def __setitem__(self, arg0: int, arg1: FrameSummary) -> None: ...
    @overload
    def __setitem__(self, arg0: slice, arg1: StackSummary) -> None: ...

def extract_stack(arg0: object, arg1: list, arg2: list) -> StackSummary: ...
