from tensorflow.python._pywrap_mlir import *
from tensorflow.python import pywrap_tensorflow as pywrap_tensorflow
from typing import Any

def import_graphdef(graphdef: Any, pass_pipeline: Any): ...
def experimental_convert_saved_model_to_mlir(saved_model_path: Any, exported_names: Any, show_debug_info: Any): ...
def experimental_convert_saved_model_v1_to_mlir(saved_model_path: Any, tags: Any, show_debug_info: Any): ...
def experimental_run_pass_pipeline(mlir_txt: Any, pass_pipeline: Any, show_debug_info: Any): ...
