from absl.flags import *
from tensorflow.python.util import tf_decorator as tf_decorator
from typing import Any

class _FlagValuesWrapper:
    def __init__(self, flags_object: Any) -> None: ...
    def __getattribute__(self, name: Any): ...
    def __getattr__(self, name: Any): ...
    def __setattr__(self, name: Any, value: Any): ...
    def __delattr__(self, name: Any): ...
    def __dir__(self): ...
    def __getitem__(self, name: Any): ...
    def __setitem__(self, name: Any, flag: Any): ...
    def __len__(self): ...
    def __iter__(self) -> Any: ...
    def __call__(self, *args: Any, **kwargs: Any): ...

DEFINE_string: Any
DEFINE_boolean: Any
DEFINE_bool = DEFINE_boolean
DEFINE_float: Any
DEFINE_integer: Any
FLAGS: Any
