from tensorflow.core.framework import types_pb2 as types_pb2
from tensorflow.lite.python import util as util
from tensorflow.python.client import session as session
from tensorflow.python.framework import ops as ops
from tensorflow.python.saved_model import constants as constants, loader as loader
from typing import Any

def get_meta_graph_def(saved_model_dir: Any, tag_set: Any): ...
def get_signature_def(meta_graph: Any, signature_key: Any): ...
def get_inputs_outputs(signature_def: Any): ...
def freeze_saved_model(saved_model_dir: Any, input_arrays: Any, input_shapes: Any, output_arrays: Any, tag_set: Any, signature_key: Any): ...
