from tensorflow.python import pywrap_tensorflow as pywrap_tensorflow
from typing import Any

def wrapped_toco_convert(model_flags_str: Any, toco_flags_str: Any, input_data_str: Any, debug_info_str: Any, enable_mlir_converter: Any): ...
def wrapped_get_potentially_supported_ops(): ...
