from typing import Any, Optional

class SaveSpec:
    slice_spec: Any = ...
    name: Any = ...
    dtype: Any = ...
    device: Any = ...
    def __init__(self, tensor: Any, slice_spec: Any, name: Any, dtype: Optional[Any] = ..., device: Optional[Any] = ...) -> None: ...
    @property
    def tensor(self): ...

class SaveableObject:
    op: Any = ...
    specs: Any = ...
    name: Any = ...
    def __init__(self, op: Any, specs: Any, name: Any) -> None: ...
    @property
    def optional_restore(self): ...
    @property
    def device(self): ...
    def restore(self, restored_tensors: Any, restored_shapes: Any) -> None: ...
