from tensorflow.python.eager import context as context
from tensorflow.python.framework import ops as ops
from tensorflow.python.ops import array_ops as array_ops, resource_variable_ops as resource_variable_ops, state_ops as state_ops, variables as variables
from tensorflow.python.training.saving import saveable_object as saveable_object
from tensorflow.python.util import nest as nest, object_identity as object_identity
from typing import Any

def set_cpu0(device_string: Any): ...

class ReferenceVariableSaveable(saveable_object.SaveableObject):
    def __init__(self, var: Any, slice_spec: Any, name: Any) -> None: ...
    def restore(self, restored_tensors: Any, restored_shapes: Any): ...

class ResourceVariableSaveable(saveable_object.SaveableObject):
    handle_op: Any = ...
    def __init__(self, var: Any, slice_spec: Any, name: Any): ...
    def restore(self, restored_tensors: Any, restored_shapes: Any): ...

def saveable_objects_for_op(op: Any, name: Any) -> None: ...
def op_list_to_dict(op_list: Any, convert_variable_to_tensor: bool = ...): ...
def validate_and_slice_inputs(names_to_saveables: Any): ...
