from tensorflow.python.eager import context as context
from tensorflow.python.framework import ops as ops
from typing import Any, Optional

def canonicalize(d: Any, default: Optional[Any] = ...): ...
def resolve(d: Any): ...

class _FakeNodeDef:
    op: str = ...
    name: str = ...
    def __init__(self) -> None: ...

class _FakeOperation:
    device: str = ...
    type: str = ...
    name: str = ...
    node_def: Any = ...
    def __init__(self) -> None: ...

def current(): ...
def get_host_for_device(device: Any): ...
def local_devices_from_num_gpus(num_gpus: Any): ...
