from typing import Any

class Process:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

def get_user_data() -> None: ...
def context_manager() -> None: ...
def using_context_manager() -> None: ...
