from tensorflow.core.protobuf import cluster_pb2 as cluster_pb2
from tensorflow.python.training import server_lib as server_lib
from typing import Any, Optional

def normalize_cluster_spec(cluster_spec: Any): ...
def is_chief(cluster_spec: Optional[Any] = ..., task_type: Optional[Any] = ..., task_id: Optional[Any] = ...): ...
def collective_leader(cluster_spec: Any, task_type: Any, task_id: Any): ...
def worker_count(cluster_spec: Any, task_type: Any): ...
def id_in_cluster(cluster_spec: Any, task_type: Any, task_id: Any): ...
def should_save_checkpoint(): ...
def should_load_checkpoint(): ...
def wait_for_other_workers(): ...
def has_worker_context(): ...
