from tensorflow.python.framework import tensor_shape as tensor_shape
from tensorflow.python.training.saving import saveable_object_util as saveable_object_util
from tensorflow.python.training.tracking import base as trackable
from typing import Any

class ShardedVariable(trackable.Trackable):
    def __init__(self, variables: Any, name: str = ...) -> None: ...
    @property
    def variables(self): ...
    @property
    def name(self): ...
    @property
    def dtype(self): ...
    @property
    def shape(self): ...
