from tensorflow.python.eager import backprop as backprop
from typing import Any

class Step:
    def __init__(self, distribution: Any) -> None: ...
    @property
    def distribution(self): ...
    def initialize(self): ...
    def __call__(self) -> None: ...

class StandardInputStep(Step):
    def __init__(self, dataset_fn: Any, distribution: Any): ...
    def initialize(self): ...

class StandardSingleLossStep(StandardInputStep):
    def __init__(self, dataset_fn: Any, loss_fn: Any, optimizer: Any, distribution: Any, iterations_per_step: int = ...) -> None: ...
    def __call__(self): ...
