from tensorflow.core.protobuf import trackable_object_graph_pb2 as trackable_object_graph_pb2
from tensorflow.python.framework import constant_op as constant_op, dtypes as dtypes, ops as ops
from tensorflow.python.training.saving import saveable_object_util as saveable_object_util
from tensorflow.python.training.tracking import base as base, tracking as tracking
from tensorflow.python.util import object_identity as object_identity
from typing import Any, Optional

class ObjectGraphView:
    def __init__(self, root: Any, saveables_cache: Optional[Any] = ...) -> None: ...
    def list_dependencies(self, obj: Any): ...
    @property
    def saveables_cache(self): ...
    @property
    def root(self): ...
    def serialize_object_graph(self): ...
    def frozen_saveable_objects(self, object_map: Optional[Any] = ..., to_graph: Optional[Any] = ...): ...
    def objects_ids_and_slot_variables(self): ...
    def list_objects(self): ...
