from tensorflow.python.eager import context as context, def_function as def_function
from tensorflow.python.framework import dtypes as dtypes, ops as ops
from tensorflow.python.training.tracking import base as base, data_structures as data_structures
from tensorflow.python.util import tf_contextlib as tf_contextlib
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any, Optional

class NotTrackable: ...

class AutoTrackable(base.Trackable):
    def __setattr__(self, name: Any, value: Any) -> None: ...
    def __delattr__(self, name: Any) -> None: ...

def delete_tracking(obj: Any, name: Any) -> None: ...

class ResourceTracker:
    def __init__(self) -> None: ...
    @property
    def resources(self): ...
    def add_resource(self, resource: Any) -> None: ...

def resource_tracker_scope(resource_tracker: Any) -> None: ...

class CapturableResourceDeleter:
    def __init__(self, destroy_resource_fn: Optional[Any] = ...) -> None: ...
    def destroy_resource(self): ...
    def __del__(self) -> None: ...

class CapturableResource(base.Trackable):
    def __init__(self, device: str = ..., deleter: Optional[Any] = ...) -> None: ...
    @property
    def resource_handle(self): ...

class TrackableResource(CapturableResource):
    def __init__(self, device: str = ..., deleter: Optional[Any] = ...) -> None: ...

class Asset(base.Trackable):
    def __init__(self, path: Any) -> None: ...
    @property
    def asset_path(self): ...

def cached_per_instance(f: Any): ...
