from tensorflow.python.framework import dtypes as dtypes, ops as ops, tensor_shape as tensor_shape
from tensorflow.python.keras.engine.base_layer import Layer as Layer
from tensorflow.python.keras.utils import tf_utils as tf_utils
from tensorflow.python.ops import array_ops as array_ops, init_ops as init_ops, math_ops as math_ops, nn as nn
from tensorflow.python.util.tf_export import keras_export as keras_export
from typing import Any, Optional

class BaseDenseAttention(Layer):
    causal: Any = ...
    dropout: Any = ...
    supports_masking: bool = ...
    def __init__(self, causal: bool = ..., dropout: float = ..., **kwargs: Any) -> None: ...
    def call(self, inputs: Any, mask: Optional[Any] = ..., training: Optional[Any] = ...): ...
    def compute_mask(self, inputs: Any, mask: Optional[Any] = ...): ...
    def get_config(self): ...

class Attention(BaseDenseAttention):
    use_scale: Any = ...
    def __init__(self, use_scale: bool = ..., **kwargs: Any) -> None: ...
    scale: Any = ...
    def build(self, input_shape: Any) -> None: ...
    def get_config(self): ...

class AdditiveAttention(BaseDenseAttention):
    use_scale: Any = ...
    def __init__(self, use_scale: bool = ..., **kwargs: Any) -> None: ...
    scale: Any = ...
    def build(self, input_shape: Any) -> None: ...
    def get_config(self): ...
