from tensorflow.python.framework import tensor_shape as tensor_shape
from tensorflow.python.keras.engine.base_layer import Layer as Layer
from tensorflow.python.keras.engine.input_spec import InputSpec as InputSpec
from tensorflow.python.keras.utils import generic_utils as generic_utils, layer_utils as layer_utils, tf_utils as tf_utils
from tensorflow.python.ops import array_ops as array_ops
from tensorflow.python.ops.ragged import ragged_tensor as ragged_tensor
from tensorflow.python.util import nest as nest, tf_inspect as tf_inspect
from tensorflow.python.util.tf_export import keras_export as keras_export
from typing import Any, Optional

class Wrapper(Layer):
    layer: Any = ...
    def __init__(self, layer: Any, **kwargs: Any) -> None: ...
    built: bool = ...
    def build(self, input_shape: Optional[Any] = ...) -> None: ...
    @property
    def activity_regularizer(self): ...
    def get_config(self): ...
    @classmethod
    def from_config(cls, config: Any, custom_objects: Optional[Any] = ...): ...

class TimeDistributed(Wrapper):
    supports_masking: bool = ...
    def __init__(self, layer: Any, **kwargs: Any) -> None: ...
    input_spec: Any = ...
    built: bool = ...
    def build(self, input_shape: Any) -> None: ...
    def compute_output_shape(self, input_shape: Any): ...
    def call(self, inputs: Any, training: Optional[Any] = ..., mask: Optional[Any] = ...): ...
    def compute_mask(self, inputs: Any, mask: Optional[Any] = ...): ...

class Bidirectional(Wrapper):
    forward_layer: Any = ...
    backward_layer: Any = ...
    merge_mode: Any = ...
    stateful: Any = ...
    return_sequences: Any = ...
    return_state: Any = ...
    supports_masking: bool = ...
    input_spec: Any = ...
    def __init__(self, layer: Any, merge_mode: str = ..., weights: Optional[Any] = ..., backward_layer: Optional[Any] = ..., **kwargs: Any) -> None: ...
    def compute_output_shape(self, input_shape: Any): ...
    def __call__(self, inputs: Any, initial_state: Optional[Any] = ..., constants: Optional[Any] = ..., **kwargs: Any): ...
    def call(self, inputs: Any, training: Optional[Any] = ..., mask: Optional[Any] = ..., initial_state: Optional[Any] = ..., constants: Optional[Any] = ...): ...
    def reset_states(self) -> None: ...
    built: bool = ...
    def build(self, input_shape: Any) -> None: ...
    def compute_mask(self, inputs: Any, mask: Any): ...
    @property
    def constraints(self): ...
    def get_config(self): ...
    @classmethod
    def from_config(cls, config: Any, custom_objects: Optional[Any] = ...): ...
