from typing import Any

def SWIG_PyInstanceMethod_New(*args, **kwargs) -> Any: ...
def get_linked_tensorrt_version(*args, **kwargs) -> Any: ...
def get_loaded_tensorrt_version(*args, **kwargs) -> Any: ...
def is_tensorrt_enabled(*args, **kwargs) -> Any: ...
