from tensorflow.python.keras.utils.generic_utils import deserialize_keras_object as deserialize_keras_object, serialize_keras_object as serialize_keras_object
from tensorflow.python.ops import math_ops as math_ops, nn as nn
from tensorflow.python.util.tf_export import keras_export as keras_export
from typing import Any, Optional

def softmax(x: Any, axis: int = ...): ...
def elu(x: Any, alpha: float = ...): ...
def selu(x: Any): ...
def softplus(x: Any): ...
def softsign(x: Any): ...
def swish(x: Any): ...
def relu(x: Any, alpha: float = ..., max_value: Optional[Any] = ..., threshold: int = ...): ...
def tanh(x: Any): ...
def sigmoid(x: Any): ...
def exponential(x: Any): ...
def hard_sigmoid(x: Any): ...
def linear(x: Any): ...
def serialize(activation: Any): ...
def deserialize(name: Any, custom_objects: Optional[Any] = ...): ...
def get(identifier: Any): ...
