from tensorflow.python.util.tf_export import keras_export as keras_export
from typing import Any

def epsilon(): ...
def set_epsilon(value: Any) -> None: ...
def floatx(): ...
def set_floatx(value: Any) -> None: ...
def image_data_format(): ...
def set_image_data_format(data_format: Any) -> None: ...
