from tensorflow.python.data.ops import iterator_ops as iterator_ops
from tensorflow.python.distribute import distributed_file_utils as distributed_file_utils, multi_worker_util as multi_worker_util
from tensorflow.python.eager import context as context
from tensorflow.python.framework import ops as ops
from tensorflow.python.keras.utils import generic_utils as generic_utils, tf_utils as tf_utils
from tensorflow.python.keras.utils.data_utils import Sequence as Sequence
from tensorflow.python.keras.utils.generic_utils import Progbar as Progbar
from tensorflow.python.keras.utils.mode_keys import ModeKeys as ModeKeys
from tensorflow.python.lib.io import file_io as file_io
from tensorflow.python.ops import array_ops as array_ops, control_flow_ops as control_flow_ops, math_ops as math_ops, summary_ops_v2 as summary_ops_v2, variables as variables
from tensorflow.python.training import checkpoint_management as checkpoint_management
from tensorflow.python.util import nest as nest
from tensorflow.python.util.compat import collections_abc as collections_abc
from tensorflow.python.util.tf_export import keras_export as keras_export
from tensorflow.tools.docs import doc_controls as doc_controls
from typing import Any, Optional

def configure_callbacks(callbacks: Any, model: Any, do_validation: bool = ..., batch_size: Optional[Any] = ..., epochs: Optional[Any] = ..., steps_per_epoch: Optional[Any] = ..., samples: Optional[Any] = ..., verbose: int = ..., count_mode: str = ..., mode: Any = ...): ...
def set_callback_parameters(callback_list: Any, model: Any, do_validation: bool = ..., batch_size: Optional[Any] = ..., epochs: Optional[Any] = ..., steps_per_epoch: Optional[Any] = ..., samples: Optional[Any] = ..., verbose: int = ..., mode: Any = ...) -> None: ...
def make_logs(model: Any, logs: Any, outputs: Any, mode: Any, prefix: str = ...): ...

class CallbackList:
    callbacks: Any = ...
    def __init__(self, callbacks: Optional[Any] = ..., add_history: bool = ..., add_progbar: bool = ..., model: Optional[Any] = ..., **params: Any) -> None: ...
    def append(self, callback: Any) -> None: ...
    params: Any = ...
    def set_params(self, params: Any) -> None: ...
    model: Any = ...
    def set_model(self, model: Any) -> None: ...
    def on_batch_begin(self, batch: Any, logs: Optional[Any] = ...) -> None: ...
    def on_batch_end(self, batch: Any, logs: Optional[Any] = ...) -> None: ...
    def on_epoch_begin(self, epoch: Any, logs: Optional[Any] = ...) -> None: ...
    def on_epoch_end(self, epoch: Any, logs: Optional[Any] = ...) -> None: ...
    def on_train_batch_begin(self, batch: Any, logs: Optional[Any] = ...) -> None: ...
    def on_train_batch_end(self, batch: Any, logs: Optional[Any] = ...) -> None: ...
    def on_test_batch_begin(self, batch: Any, logs: Optional[Any] = ...) -> None: ...
    def on_test_batch_end(self, batch: Any, logs: Optional[Any] = ...) -> None: ...
    def on_predict_batch_begin(self, batch: Any, logs: Optional[Any] = ...) -> None: ...
    def on_predict_batch_end(self, batch: Any, logs: Optional[Any] = ...) -> None: ...
    def on_train_begin(self, logs: Optional[Any] = ...) -> None: ...
    def on_train_end(self, logs: Optional[Any] = ...) -> None: ...
    def on_test_begin(self, logs: Optional[Any] = ...) -> None: ...
    def on_test_end(self, logs: Optional[Any] = ...) -> None: ...
    def on_predict_begin(self, logs: Optional[Any] = ...) -> None: ...
    def on_predict_end(self, logs: Optional[Any] = ...) -> None: ...
    def __iter__(self) -> Any: ...

class Callback:
    validation_data: Any = ...
    model: Any = ...
    def __init__(self) -> None: ...
    params: Any = ...
    def set_params(self, params: Any) -> None: ...
    def set_model(self, model: Any) -> None: ...
    def on_batch_begin(self, batch: Any, logs: Optional[Any] = ...) -> None: ...
    def on_batch_end(self, batch: Any, logs: Optional[Any] = ...) -> None: ...
    def on_epoch_begin(self, epoch: Any, logs: Optional[Any] = ...) -> None: ...
    def on_epoch_end(self, epoch: Any, logs: Optional[Any] = ...) -> None: ...
    def on_train_batch_begin(self, batch: Any, logs: Optional[Any] = ...) -> None: ...
    def on_train_batch_end(self, batch: Any, logs: Optional[Any] = ...) -> None: ...
    def on_test_batch_begin(self, batch: Any, logs: Optional[Any] = ...) -> None: ...
    def on_test_batch_end(self, batch: Any, logs: Optional[Any] = ...) -> None: ...
    def on_predict_batch_begin(self, batch: Any, logs: Optional[Any] = ...) -> None: ...
    def on_predict_batch_end(self, batch: Any, logs: Optional[Any] = ...) -> None: ...
    def on_train_begin(self, logs: Optional[Any] = ...) -> None: ...
    def on_train_end(self, logs: Optional[Any] = ...) -> None: ...
    def on_test_begin(self, logs: Optional[Any] = ...) -> None: ...
    def on_test_end(self, logs: Optional[Any] = ...) -> None: ...
    def on_predict_begin(self, logs: Optional[Any] = ...) -> None: ...
    def on_predict_end(self, logs: Optional[Any] = ...) -> None: ...

class BaseLogger(Callback):
    stateful_metrics: Any = ...
    def __init__(self, stateful_metrics: Optional[Any] = ...) -> None: ...
    seen: int = ...
    totals: Any = ...
    def on_epoch_begin(self, epoch: Any, logs: Optional[Any] = ...) -> None: ...
    def on_batch_end(self, batch: Any, logs: Optional[Any] = ...) -> None: ...
    def on_epoch_end(self, epoch: Any, logs: Optional[Any] = ...) -> None: ...

class TerminateOnNaN(Callback):
    def on_batch_end(self, batch: Any, logs: Optional[Any] = ...) -> None: ...

class ProgbarLogger(Callback):
    use_steps: bool = ...
    stateful_metrics: Any = ...
    seen: int = ...
    progbar: Any = ...
    target: Any = ...
    verbose: int = ...
    epochs: int = ...
    def __init__(self, count_mode: str = ..., stateful_metrics: Optional[Any] = ...) -> None: ...
    def set_params(self, params: Any) -> None: ...
    def on_train_begin(self, logs: Optional[Any] = ...) -> None: ...
    def on_test_begin(self, logs: Optional[Any] = ...) -> None: ...
    def on_predict_begin(self, logs: Optional[Any] = ...) -> None: ...
    def on_epoch_begin(self, epoch: Any, logs: Optional[Any] = ...) -> None: ...
    def on_train_batch_end(self, batch: Any, logs: Optional[Any] = ...) -> None: ...
    def on_test_batch_end(self, batch: Any, logs: Optional[Any] = ...) -> None: ...
    def on_predict_batch_end(self, batch: Any, logs: Optional[Any] = ...) -> None: ...
    def on_epoch_end(self, epoch: Any, logs: Optional[Any] = ...) -> None: ...
    def on_test_end(self, logs: Optional[Any] = ...) -> None: ...
    def on_predict_end(self, logs: Optional[Any] = ...) -> None: ...

class History(Callback):
    history: Any = ...
    def __init__(self) -> None: ...
    epoch: Any = ...
    def on_train_begin(self, logs: Optional[Any] = ...) -> None: ...
    def on_epoch_end(self, epoch: Any, logs: Optional[Any] = ...) -> None: ...

class ModelCheckpoint(Callback):
    monitor: Any = ...
    verbose: Any = ...
    filepath: Any = ...
    save_best_only: Any = ...
    save_weights_only: Any = ...
    save_freq: Any = ...
    epochs_since_last_save: int = ...
    load_weights_on_restart: Any = ...
    period: Any = ...
    monitor_op: Any = ...
    best: Any = ...
    def __init__(self, filepath: Any, monitor: str = ..., verbose: int = ..., save_best_only: bool = ..., save_weights_only: bool = ..., mode: str = ..., save_freq: str = ..., **kwargs: Any) -> None: ...
    model: Any = ...
    def set_model(self, model: Any) -> None: ...
    def on_train_begin(self, logs: Optional[Any] = ...) -> None: ...
    def on_train_end(self, logs: Optional[Any] = ...) -> None: ...
    def on_batch_end(self, batch: Any, logs: Optional[Any] = ...) -> None: ...
    def on_epoch_begin(self, epoch: Any, logs: Optional[Any] = ...) -> None: ...
    def on_epoch_end(self, epoch: Any, logs: Optional[Any] = ...) -> None: ...

class EarlyStopping(Callback):
    monitor: Any = ...
    patience: Any = ...
    verbose: Any = ...
    baseline: Any = ...
    min_delta: Any = ...
    wait: int = ...
    stopped_epoch: int = ...
    restore_best_weights: Any = ...
    best_weights: Any = ...
    monitor_op: Any = ...
    def __init__(self, monitor: str = ..., min_delta: int = ..., patience: int = ..., verbose: int = ..., mode: str = ..., baseline: Optional[Any] = ..., restore_best_weights: bool = ...) -> None: ...
    best: Any = ...
    def on_train_begin(self, logs: Optional[Any] = ...) -> None: ...
    def on_epoch_end(self, epoch: Any, logs: Optional[Any] = ...) -> None: ...
    def on_train_end(self, logs: Optional[Any] = ...) -> None: ...
    def get_monitor_value(self, logs: Any): ...

class RemoteMonitor(Callback):
    root: Any = ...
    path: Any = ...
    field: Any = ...
    headers: Any = ...
    send_as_json: Any = ...
    def __init__(self, root: str = ..., path: str = ..., field: str = ..., headers: Optional[Any] = ..., send_as_json: bool = ...) -> None: ...
    def on_epoch_end(self, epoch: Any, logs: Optional[Any] = ...) -> None: ...

class LearningRateScheduler(Callback):
    schedule: Any = ...
    verbose: Any = ...
    def __init__(self, schedule: Any, verbose: int = ...) -> None: ...
    def on_epoch_begin(self, epoch: Any, logs: Optional[Any] = ...) -> None: ...
    def on_epoch_end(self, epoch: Any, logs: Optional[Any] = ...) -> None: ...

class TensorBoard(Callback):
    log_dir: Any = ...
    histogram_freq: Any = ...
    write_graph: Any = ...
    write_images: Any = ...
    update_freq: int = ...
    embeddings_freq: Any = ...
    embeddings_metadata: Any = ...
    def __init__(self, log_dir: str = ..., histogram_freq: int = ..., write_graph: bool = ..., write_images: bool = ..., update_freq: str = ..., profile_batch: int = ..., embeddings_freq: int = ..., embeddings_metadata: Optional[Any] = ..., **kwargs: Any) -> None: ...
    model: Any = ...
    def set_model(self, model: Any) -> None: ...
    def on_train_begin(self, logs: Optional[Any] = ...) -> None: ...
    def on_test_begin(self, logs: Optional[Any] = ...) -> None: ...
    def on_train_batch_end(self, batch: Any, logs: Optional[Any] = ...): ...
    def on_test_batch_end(self, batch: Any, logs: Optional[Any] = ...) -> None: ...
    def on_epoch_begin(self, epoch: Any, logs: Optional[Any] = ...) -> None: ...
    def on_epoch_end(self, epoch: Any, logs: Optional[Any] = ...) -> None: ...
    def on_train_end(self, logs: Optional[Any] = ...) -> None: ...

class ReduceLROnPlateau(Callback):
    monitor: Any = ...
    factor: Any = ...
    min_lr: Any = ...
    min_delta: Any = ...
    patience: Any = ...
    verbose: Any = ...
    cooldown: Any = ...
    cooldown_counter: int = ...
    wait: int = ...
    best: int = ...
    mode: Any = ...
    monitor_op: Any = ...
    def __init__(self, monitor: str = ..., factor: float = ..., patience: int = ..., verbose: int = ..., mode: str = ..., min_delta: float = ..., cooldown: int = ..., min_lr: int = ..., **kwargs: Any) -> None: ...
    def on_train_begin(self, logs: Optional[Any] = ...) -> None: ...
    def on_epoch_end(self, epoch: Any, logs: Optional[Any] = ...) -> None: ...
    def in_cooldown(self): ...

class CSVLogger(Callback):
    sep: Any = ...
    filename: Any = ...
    append: Any = ...
    writer: Any = ...
    keys: Any = ...
    append_header: bool = ...
    file_flags: str = ...
    def __init__(self, filename: Any, separator: str = ..., append: bool = ...) -> None: ...
    csv_file: Any = ...
    def on_train_begin(self, logs: Optional[Any] = ...) -> None: ...
    def on_epoch_end(self, epoch: Any, logs: Optional[Any] = ...): ...
    def on_train_end(self, logs: Optional[Any] = ...) -> None: ...

class LambdaCallback(Callback):
    on_epoch_begin: Any = ...
    on_epoch_end: Any = ...
    on_batch_begin: Any = ...
    on_batch_end: Any = ...
    on_train_begin: Any = ...
    on_train_end: Any = ...
    def __init__(self, on_epoch_begin: Optional[Any] = ..., on_epoch_end: Optional[Any] = ..., on_batch_begin: Optional[Any] = ..., on_batch_end: Optional[Any] = ..., on_train_begin: Optional[Any] = ..., on_train_end: Optional[Any] = ..., **kwargs: Any) -> None: ...
