from tensorflow.python.framework import tensor_util as tensor_util
from tensorflow.python.ops import control_flow_ops as control_flow_ops, gen_math_ops as gen_math_ops
from typing import Any

def not_(a: Any): ...
def and_(a: Any, b: Any): ...
def or_(a: Any, b: Any): ...
def eq(a: Any, b: Any): ...
def not_eq(a: Any, b: Any): ...
