from typing import Any

class Undefined:
    symbol_name: Any = ...
    def __init__(self, symbol_name: Any) -> None: ...
    def __getattribute__(self, name: Any): ...
    def __getitem__(self, i: Any): ...

def is_undefined(value: Any): ...

class UndefinedReturnValue: ...

def retval(value: Any): ...
def is_undefined_return(value: Any): ...
