from tensorflow.python.autograph.operators import special_values as special_values
from typing import Any

is_undefined = special_values.is_undefined
Undefined = special_values.Undefined

class Symbol:
    name: Any = ...
    def __init__(self, name: Any) -> None: ...

class ValueSymbol(Symbol):
    value: Any = ...
    def __init__(self, name: Any, value: Any) -> None: ...
    def maybe_compute_value(self): ...

class AttributeAccessSymbol(Symbol):
    attr_name: Any = ...
    parent_symbol: Any = ...
    def __init__(self, parent_symbol: Any, attr_name: Any) -> None: ...
    def maybe_compute_value(self): ...

class SubscriptSymbol(Symbol):
    index_symbol: Any = ...
    parent_symbol: Any = ...
    def __init__(self, parent_symbol: Any, index_symbol: Any) -> None: ...
    def maybe_compute_value(self): ...
