from ..compat import collections_abc as collections_abc
from typing import Any, Optional

def assertProtoEqual(self, a: Any, b: Any, check_initialized: bool = ..., normalize_numbers: bool = ..., msg: Optional[Any] = ...) -> None: ...
def NormalizeNumberFields(pb: Any): ...
def ProtoEq(a: Any, b: Any): ...

class ProtoAssertions:
    def assertProtoEqual(self, *args: Any, **kwargs: Any): ...
