from tensorflow.python.ops.distributions import distribution
from typing import Any

class Gamma(distribution.Distribution):
    def __init__(self, concentration: Any, rate: Any, validate_args: bool = ..., allow_nan_stats: bool = ..., name: str = ...) -> None: ...
    @property
    def concentration(self): ...
    @property
    def rate(self): ...

class GammaWithSoftplusConcentrationRate(Gamma):
    def __init__(self, concentration: Any, rate: Any, validate_args: bool = ..., allow_nan_stats: bool = ..., name: str = ...) -> None: ...
