from typing import Any, Optional

def kl_divergence(distribution_a: Any, distribution_b: Any, allow_nan_stats: bool = ..., name: Optional[Any] = ...): ...

class RegisterKL:
    def __init__(self, dist_cls_a: Any, dist_cls_b: Any) -> None: ...
    def __call__(self, kl_fn: Any): ...
