from typing import Any

def ndtr(x: Any, name: str = ...): ...
def ndtri(p: Any, name: str = ...): ...
def log_ndtr(x: Any, series_order: int = ..., name: str = ...): ...
def erfinv(x: Any, name: str = ...): ...
def log_cdf_laplace(x: Any, name: str = ...): ...
