from typing import Any

def do_not_generate_docs(obj: Any): ...
def do_not_doc_inheritable(obj: Any): ...
def for_subclass_implementers(obj: Any): ...
do_not_doc_in_subclasses = for_subclass_implementers

def should_skip(obj: Any): ...
def should_skip_class_attr(cls, name: Any): ...
