from typing import Any

def md_files_in_dir(py_guide_src_dir: Any): ...

class PyGuideParser:
    def __init__(self) -> None: ...
    def process(self, full_path: Any): ...
    def replace_line(self, line_number: Any, line: Any) -> None: ...
    def process_title(self, line_number: Any, title: Any) -> None: ...
    def process_section(self, line_number: Any, section_title: Any, tag: Any) -> None: ...
    def process_in_blockquote(self, line_number: Any, line: Any) -> None: ...
    def process_line(self, line_number: Any, line: Any) -> None: ...
