from tensorflow.python.framework import errors as errors
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any

def start(logdir: Any) -> None: ...
def stop(save: bool = ...) -> None: ...
def warmup() -> None: ...
def start_server(port: Any) -> None: ...

class Profile:
    def __init__(self, logdir: Any) -> None: ...
    def __enter__(self) -> None: ...
    def __exit__(self, typ: Any, value: Any, tb: Any) -> None: ...
