from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any

def trace(service_addr: Any, logdir: Any, duration_ms: Any, worker_list: str = ..., num_tracing_attempts: int = ...) -> None: ...
def monitor(service_addr: Any, duration_ms: Any, level: int = ...): ...
