from tensorflow.python.autograph.core import converter as converter
from tensorflow.python.autograph.pyct import parser as parser
from typing import Any

class _Function: ...

class ArgDefaultsTransformer(converter.Base):
    def visit_Lambda(self, node: Any): ...
    def visit_FunctionDef(self, node: Any): ...
    def visit_arguments(self, node: Any): ...

def transform(node: Any, ctx: Any): ...
