from tensorflow.python.autograph.core import converter as converter
from tensorflow.python.autograph.lang import directives as directives
from tensorflow.python.autograph.pyct import anno as anno, ast_util as ast_util, parser as parser, templates as templates
from tensorflow.python.autograph.pyct.static_analysis import annos as annos
from typing import Any

class ControlFlowTransformer(converter.Base):
    def visit_If(self, node: Any): ...
    def visit_While(self, node: Any): ...
    def visit_For(self, node: Any): ...

def transform(node: Any, ctx: Any): ...
