from tensorflow.python.autograph.core import converter as converter
from tensorflow.python.autograph.pyct import anno as anno, templates as templates
from tensorflow.python.autograph.pyct.static_analysis.annos import NodeAnno as NodeAnno
from typing import Any

class _Continue:
    used: bool = ...
    control_var_name: Any = ...
    def __init__(self) -> None: ...

class _Block:
    is_loop_type: bool = ...
    create_guard_current: bool = ...
    create_guard_next: bool = ...
    def __init__(self) -> None: ...

class ContinueCanonicalizationTransformer(converter.Base):
    def visit_Continue(self, node: Any): ...
    def visit_While(self, node: Any): ...
    def visit_For(self, node: Any): ...
    def visit_If(self, node: Any): ...
    def visit_With(self, node: Any): ...
    def visit_Try(self, node: Any): ...
    def visit_ExceptHandler(self, node: Any): ...

def transform(node: Any, ctx: Any): ...
