from tensorflow.python.autograph.core import converter as converter
from tensorflow.python.autograph.lang import directives as directives
from tensorflow.python.autograph.pyct import anno as anno, ast_util as ast_util, parser as parser, templates as templates
from tensorflow.python.autograph.pyct.static_analysis import annos as annos
from tensorflow.python.autograph.utils import compat_util as compat_util
from typing import Any

class _Function:
    scope: Any = ...

class ControlFlowTransformer(converter.Base):
    def visit_Lambda(self, node: Any): ...
    def visit_FunctionDef(self, node: Any): ...
    def visit_If(self, node: Any): ...
    def visit_While(self, node: Any): ...
    def visit_For(self, node: Any): ...

def transform(node: Any, ctx: Any): ...
