from tensorflow.python.autograph.core import converter as converter
from tensorflow.python.autograph.pyct import anno as anno, templates as templates
from tensorflow.python.autograph.pyct.static_analysis import annos as annos
from typing import Any

class _Function:
    context_name: Any = ...
    def __init__(self) -> None: ...

class FunctionBodyTransformer(converter.Base):
    def visit_Return(self, node: Any): ...
    def visit_Lambda(self, node: Any): ...
    def visit_FunctionDef(self, node: Any): ...

def transform(node: Any, ctx: Any): ...
