from google.protobuf.any_pb2 import Any
from tensorflow.core.framework import types_pb2 as types_pb2
from tensorflow.core.protobuf import meta_graph_pb2 as meta_graph_pb2, saved_model_pb2 as saved_model_pb2, saver_pb2 as saver_pb2
from tensorflow.python.framework import dtypes as dtypes, ops as ops
from tensorflow.python.lib.io import file_io as file_io
from tensorflow.python.ops import variables as variables
from tensorflow.python.platform import tf_logging as tf_logging
from tensorflow.python.saved_model import constants as constants, signature_def_utils as signature_def_utils
from tensorflow.python.util import compat as compat
from tensorflow.python.util.deprecation import deprecated_args as deprecated_args
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Optional

class _SavedModelBuilder:
    def __init__(self, export_dir: Any) -> None: ...
    def add_meta_graph(self, tags: Any, signature_def_map: Optional[Any] = ..., assets_list: Optional[Any] = ..., clear_devices: bool = ..., init_op: Optional[Any] = ..., train_op: Optional[Any] = ..., saver: Optional[Any] = ...) -> None: ...
    def add_meta_graph_and_variables(self, sess: Any, tags: Any, signature_def_map: Optional[Any] = ..., assets_list: Optional[Any] = ..., clear_devices: bool = ..., init_op: Optional[Any] = ..., train_op: Optional[Any] = ..., strip_default_attrs: bool = ..., saver: Optional[Any] = ...) -> None: ...
    def save(self, as_text: bool = ...): ...

class SavedModelBuilder(_SavedModelBuilder):
    __doc__: Any = ...
    def __init__(self, export_dir: Any) -> None: ...
    def add_meta_graph(self, tags: Any, signature_def_map: Optional[Any] = ..., assets_collection: Optional[Any] = ..., legacy_init_op: Optional[Any] = ..., clear_devices: bool = ..., main_op: Optional[Any] = ..., strip_default_attrs: bool = ..., saver: Optional[Any] = ...) -> None: ...
    def add_meta_graph_and_variables(self, sess: Any, tags: Any, signature_def_map: Optional[Any] = ..., assets_collection: Optional[Any] = ..., legacy_init_op: Optional[Any] = ..., clear_devices: bool = ..., main_op: Optional[Any] = ..., strip_default_attrs: bool = ..., saver: Optional[Any] = ...) -> None: ...

def get_asset_filename_to_add(asset_filepath: Any, asset_filename_map: Any): ...
def copy_assets_to_destination_dir(asset_filename_map: Any, destination_dir: Any) -> None: ...
