from tensorflow.python.util.tf_export import tf_export as tf_export

ASSETS_DIRECTORY: str
EXTRA_ASSETS_DIRECTORY: str
ASSETS_KEY: str
LEGACY_INIT_OP_KEY: str
MAIN_OP_KEY: str
TRAIN_OP_KEY: str
SAVED_MODEL_SCHEMA_VERSION: int
SAVED_MODEL_FILENAME_PB: str
SAVED_MODEL_FILENAME_PBTXT: str
DEBUG_DIRECTORY: str
DEBUG_INFO_FILENAME_PB: str
SAVED_MODEL_FILENAME_JSON: str
VARIABLES_DIRECTORY: str
VARIABLES_FILENAME: str
INIT_OP_SIGNATURE_KEY: str
TRAIN_OP_SIGNATURE_KEY: str
