from tensorflow.core.framework import function_pb2 as function_pb2
from tensorflow.python.eager import context as context, def_function as def_function
from tensorflow.python.framework import ops as ops, tensor_spec as tensor_spec, type_spec as type_spec
from tensorflow.python.ops import resource_variable_ops as resource_variable_ops
from tensorflow.python.saved_model import nested_structure_coder as nested_structure_coder
from tensorflow.python.util import compat as compat, nest as nest, tf_decorator as tf_decorator, tf_inspect as tf_inspect
from typing import Any, Optional

def setup_bare_concrete_function(saved_bare_concrete_function: Any, concrete_functions: Any): ...

class RestoredFunction(def_function.Function):
    concrete_functions: Any = ...
    def __init__(self, python_function: Any, name: Any, function_spec: Any, concrete_functions: Any) -> None: ...

def recreate_function(saved_function: Any, concrete_functions: Any): ...
def load_function_def_library(library: Any, load_shared_name_suffix: Optional[Any] = ...): ...
def fix_node_def(node_def: Any, functions: Any, shared_name_suffix: Any, debug_name: Any) -> None: ...
