from tensorflow.core.framework import versions_pb2 as versions_pb2
from tensorflow.core.protobuf import saved_object_graph_pb2 as saved_object_graph_pb2
from typing import Any, Optional

class VersionedTypeRegistration:
    setter: Any = ...
    identifier: Any = ...
    version: Any = ...
    def __init__(self, object_factory: Any, version: Any, min_producer_version: Any, min_consumer_version: Any, bad_consumers: Optional[Any] = ..., setter: Any = ...) -> None: ...
    def to_proto(self): ...
    def from_proto(self, proto: Any): ...
    def should_load(self, proto: Any): ...

def register_revived_type(identifier: Any, predicate: Any, versions: Any): ...
def serialize(obj: Any): ...
def deserialize(proto: Any): ...
def registered_identifiers(): ...
def get_setter(proto: Any): ...
