from tensorflow.python.util import compat as compat
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any, Optional

class SaveOptions:
    namespace_whitelist: Any = ...
    save_debug_info: Any = ...
    function_aliases: Any = ...
    def __init__(self, namespace_whitelist: Optional[Any] = ..., save_debug_info: bool = ..., function_aliases: Optional[Any] = ...) -> None: ...
