from tensorflow.python.eager import def_function as def_function
from tensorflow.python.framework import ops as ops, tensor_spec as tensor_spec
from tensorflow.python.ops import resource_variable_ops as resource_variable_ops
from tensorflow.python.saved_model import function_serialization as function_serialization, revived_types as revived_types, signature_constants as signature_constants
from tensorflow.python.training.tracking import base as base
from tensorflow.python.util import compat as compat, nest as nest
from tensorflow.python.util.compat import collections_abc as collections_abc
from typing import Any

DEFAULT_SIGNATURE_ATTR: str
SIGNATURE_ATTRIBUTE_NAME: str

def find_function_to_export(saveable_view: Any): ...
def canonicalize_signatures(signatures: Any): ...

class _SignatureMap(collections_abc.Mapping, base.Trackable):
    def __init__(self) -> None: ...
    def __getitem__(self, key: Any): ...
    def __iter__(self) -> Any: ...
    def __len__(self): ...

def create_signature_map(signatures: Any): ...
def validate_saveable_view(saveable_view: Any) -> None: ...
