from tensorflow.core.framework import types_pb2 as types_pb2
from tensorflow.core.protobuf import meta_graph_pb2 as meta_graph_pb2
from tensorflow.python.framework import errors as errors, ops as ops
from tensorflow.python.saved_model import signature_constants as signature_constants
from tensorflow.python.util import deprecation as deprecation
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any, Optional

def build_signature_def(inputs: Optional[Any] = ..., outputs: Optional[Any] = ..., method_name: Optional[Any] = ...): ...
def regression_signature_def(examples: Any, predictions: Any): ...
def classification_signature_def(examples: Any, classes: Any, scores: Any): ...
def predict_signature_def(inputs: Any, outputs: Any): ...
def supervised_train_signature_def(inputs: Any, loss: Any, predictions: Optional[Any] = ..., metrics: Optional[Any] = ...): ...
def supervised_eval_signature_def(inputs: Any, loss: Any, predictions: Optional[Any] = ..., metrics: Optional[Any] = ...): ...
def is_valid_signature(signature_def: Any): ...
def op_signature_def(op: Any, key: Any): ...
def load_op_from_signature_def(signature_def: Any, key: Any, import_scope: Optional[Any] = ...): ...
