from tensorflow.core.protobuf.tpu import topology_pb2 as topology_pb2
from typing import Any, Optional

class Topology:
    def __init__(self, serialized: Optional[Any] = ..., mesh_shape: Optional[Any] = ..., device_coordinates: Optional[Any] = ...) -> None: ...
    @property
    def mesh_shape(self): ...
    @property
    def mesh_rank(self): ...
    @property
    def device_coordinates(self): ...
    @property
    def missing_devices(self): ...
    def task_ordinal_at_coordinates(self, device_coordinates: Any): ...
    def tpu_device_ordinal_at_coordinates(self, device_coordinates: Any): ...
    def cpu_device_name_at_coordinates(self, device_coordinates: Any, job: Optional[Any] = ...): ...
    def tpu_device_name_at_coordinates(self, device_coordinates: Any, job: Optional[Any] = ...): ...
    @property
    def num_tasks(self): ...
    @property
    def num_tpus_per_task(self): ...
    def serialized(self): ...
