import threading
from typing import Any

class TpuContext(threading.local):
    def __init__(self) -> None: ...
    @property
    def number_of_shards(self): ...
    def set_number_of_shards(self, number_of_shards: Any) -> None: ...

def tpu_shard_context(number_of_shards: Any) -> None: ...
def get_tpu_context(): ...
def on_device_training_loop(func: Any): ...
