from tensorflow.python.framework import tensor_shape as tensor_shape
from typing import Any

def is_broadcast_compatible(shape_x: Any, shape_y: Any): ...
def broadcast_shape(shape_x: Any, shape_y: Any): ...
