from tensorflow.python.framework import composite_tensor as composite_tensor, sparse_tensor as sparse_tensor
from tensorflow.python.ops import sparse_ops as sparse_ops
from tensorflow.python.ops.ragged import ragged_concat_ops as ragged_concat_ops, ragged_tensor as ragged_tensor, ragged_tensor_value as ragged_tensor_value
from typing import Any

def is_composite_or_composite_value(tensor: Any): ...
def get_shape(tensor: Any): ...
def append_composite_tensor(target: Any, to_append: Any): ...
