from tensorflow.python.eager import context as context
from tensorflow.python.util import deprecation as deprecation
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any, Optional

def get_intra_op_parallelism_threads(): ...
def set_intra_op_parallelism_threads(num_threads: Any) -> None: ...
def get_inter_op_parallelism_threads(): ...
def set_inter_op_parallelism_threads(num_threads: Any) -> None: ...
def get_optimizer_jit(): ...
def set_optimizer_jit(enabled: Any) -> None: ...
def get_optimizer_experimental_options(): ...
def set_optimizer_experimental_options(options: Any) -> None: ...
def get_soft_device_placement(): ...
def set_soft_device_placement(enabled: Any) -> None: ...
def get_device_policy(): ...
def set_device_policy(device_policy: Any) -> None: ...
def get_synchronous_execution(): ...
def set_synchronous_execution(enable: Any) -> None: ...
def list_physical_devices(device_type: Optional[Any] = ...): ...
def list_logical_devices(device_type: Optional[Any] = ...): ...
def get_visible_devices(device_type: Optional[Any] = ...): ...
def set_visible_devices(devices: Any, device_type: Optional[Any] = ...) -> None: ...
def get_memory_growth(device: Any): ...
def set_memory_growth(device: Any, enable: Any) -> None: ...
def get_logical_device_configuration(device: Any): ...
def set_logical_device_configuration(device: Any, logical_devices: Any) -> None: ...
def enable_mlir_bridge() -> None: ...
def disable_mlir_bridge() -> None: ...
