from tensorflow.python import tf2 as tf2
from tensorflow.python.framework import device_spec as device_spec
from typing import Any

DeviceSpec = device_spec.DeviceSpecV2
DeviceSpec = device_spec.DeviceSpecV1

def check_valid(spec: Any) -> None: ...
def is_device_spec(obj: Any): ...
def canonical_name(device: Any): ...
def merge_device(spec: Any): ...

class MergeDevice:
    def __init__(self, spec: Any) -> None: ...
    def __call__(self, node_def: Any): ...
    def shortcut_string_merge(self, node_def: Any): ...
    @property
    def is_null_merge(self): ...
