from tensorflow.python.lib.io import file_io as file_io
from tensorflow.python.util import deprecation as deprecation
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any

def load_op_library(library_filename: Any): ...
def load_file_system_library(library_filename: Any) -> None: ...
def load_library(library_location: Any) -> None: ...
