import abc
from tensorflow.python.framework import common_shapes as common_shapes, dtypes as dtypes, ops as ops, tensor_shape as tensor_shape, type_spec as type_spec
from tensorflow.python.util.tf_export import tf_export as tf_export
from typing import Any, Optional

class DenseSpec(type_spec.TypeSpec, metaclass=abc.ABCMeta):
    def __init__(self, shape: Any, dtype: Any = ..., name: Optional[Any] = ...) -> None: ...
    @classmethod
    def from_spec(cls, spec: Any, name: Optional[Any] = ...): ...
    @property
    def shape(self): ...
    @property
    def dtype(self): ...
    @property
    def name(self): ...
    def is_compatible_with(self, spec_or_value: Any): ...
    def __hash__(self) -> Any: ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
    def most_specific_compatible_type(self, other: Any): ...

class TensorSpec(DenseSpec, type_spec.BatchableTypeSpec):
    def is_compatible_with(self, spec_or_tensor: Any): ...
    @classmethod
    def from_tensor(cls, tensor: Any, name: Optional[Any] = ...): ...
    value_type: Any = ...

class BoundedTensorSpec(TensorSpec):
    def __init__(self, shape: Any, dtype: Any, minimum: Any, maximum: Any, name: Optional[Any] = ...) -> None: ...
    @classmethod
    def from_spec(cls, spec: Any): ...
    @property
    def minimum(self): ...
    @property
    def maximum(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __hash__(self) -> Any: ...
    def __reduce__(self): ...
