from tensorflow.python.ops import array_ops as array_ops, math_ops as math_ops
from typing import Any

def inner_product(u: Any, v: Any): ...
def exact_gaussian_kernel(x: Any, y: Any, stddev: Any): ...
def exact_laplacian_kernel(x: Any, y: Any, stddev: Any): ...
