from tensorflow.python.util.tf_export import keras_export as keras_export
from typing import Any, Optional

def to_categorical(y: Any, num_classes: Optional[Any] = ..., dtype: str = ...): ...
def normalize(x: Any, axis: int = ..., order: int = ...): ...
