from collections import namedtuple
from typing import Any

CodeLine = namedtuple('CodeLine', ['cell_number', 'code'])

def is_python(cell: Any): ...
def process_file(in_filename: Any, out_filename: Any, upgrader: Any): ...
def skip_magic(code_line: Any, magic_list: Any): ...
def check_line_split(code_line: Any): ...
