from tensorflow.tools.compatibility import all_renames_v2 as all_renames_v2, ast_edits as ast_edits, module_deprecations_v2 as module_deprecations_v2
from typing import Any

class TFAPIChangeSpec(ast_edits.APIChangeSpec):
    function_keyword_renames: Any = ...
    symbol_renames: Any = ...
    change_to_function: Any = ...
    function_reorders: Any = ...
    function_warnings: Any = ...
    function_transformers: Any = ...
    module_deprecations: Any = ...
    import_renames: Any = ...
    max_submodule_depth: int = ...
    def __init__(self) -> None: ...
