from tensorflow.tools.compatibility import ast_edits as ast_edits, ipynb as ipynb, tf_upgrade_v2 as tf_upgrade_v2, tf_upgrade_v2_safety as tf_upgrade_v2_safety
from typing import Any

def process_file(in_filename: Any, out_filename: Any, upgrader: Any): ...
def main() -> None: ...
